STRINGS = {
    "sidebar": {
        "title": "Seitenleiste",
        "provider_select": "Anbieter",
        "model_select": "LLM auswählen",
        "llm_switch": "Analyse per LLM",
        "analyse_teacher_switch": "Lehrkraft analysieren",
        "analyse_students_switch": "Schüler:innen analysieren",
        "multi_coding_switch": "Mehrfach-Codierung erlauben",
        "prompt_filter_teacher_only": "\n\nWICHTIG: Codiere AUSSCHLIESSLICH Äußerungen der Lehrperson ({teacher_name}). Ignoriere sämtliche Äußerungen der Schüler:innen.",
        "prompt_filter_students_only": "\n\nWICHTIG: Codiere AUSSCHLIESSLICH Äußerungen der Schüler:innen. Ignoriere sämtliche Äußerungen der Lehrperson ({teacher_name}).",
        "prompt_filter_none": "\n\nWICHTIG: Es ist keine Sprechergruppe ausgewählt. Bitte aktiviere in der Seitenleiste mindestens „Lehrkraft analysieren\" oder „Schüler:innen analysieren\".",
        "user_prompt_filter_teacher_only": "\n\nBitte codiere in diesem Transkript AUSSCHLIESSLICH Äußerungen der Lehrperson ({teacher_name}). Überspringe jede Schüler-Äußerung (S01, S02, ...) vollständig.",
        "user_prompt_filter_students_only": "\n\nBitte codiere in diesem Transkript AUSSCHLIESSLICH Schüler-Äußerungen (S01, S02, ...). Überspringe jede Äußerung der Lehrperson ({teacher_name}) vollständig.",
        "user_prompt_filter_none": "\n\nEs ist aktuell keine Sprechergruppe aktiviert — es soll keine Codierung erzeugt werden.",
        "prompt_multi_coding_on": "\n\nWICHTIG: Wenn mehrere Codes aus dem Codebuch auf eine Äußerung passen, ordne die zutreffendsten zu — gib pro zutreffendem Code einen separaten Eintrag aus, mit gleichem 'Sprecher' und 'Impuls', aber unterschiedlichem 'Shortcode'. Vergib HÖCHSTENS ZWEI Codes pro Äußerung, den sichersten zuerst. Ergänze in JEDEM Eintrag als letztes Feld 'Konfidenz': eine ganze Zahl von 0 bis 100, wie sicher der Code auf die Äußerung zutrifft. KALIBRIERE die Konfidenz über die volle Skala und begründe sie dir aus der Textevidenz: 90+ NUR bei eindeutiger, wörtlich belegbarer Passung; 60–75 = plausibel, aber diskutabel; unter 50 = spekulativ. Vergib nicht denselben Standardwert für viele Äußerungen — unterschiedliche Äußerungen tragen unterschiedlich viel Evidenz. Sehr kurze Äußerungen ohne eigenständigen Inhalt rechtfertigen höchstens mittlere Konfidenz. Nenne die besten Kandidaten auch dann, wenn du unsicher bist — die Konfidenz macht die Unsicherheit transparent. Wenn eine Äußerung mehrere distinkte Aspekte oder Themen abdeckt (häufiger bei längeren Beiträgen), vergib für jeden zutreffenden Aspekt einen eigenen Code — die Länge ist nur ein Indikator, entscheidend ist die thematische Vielfalt. Wenn auf eine Äußerung erkennbar KEIN Code passt, lass sie einfach weg — sie erscheint dann mit leerem Shortcode im Report. Codiere das gesamte Transkript bis zum Ende; höre nicht früher auf.",
        "prompt_multi_coding_off": "\n\nWICHTIG: Ordne pro Äußerung HÖCHSTENS EINEN Code aus dem Codebuch zu — den passendsten. Wenn KEIN Code aus dem Codebuch passt, lass die Äußerung in der Ausgabe weg (sie erscheint dann mit leerem Shortcode im Report). Keine Mehrfach-Codierungen pro Äußerung; jede Äußerung erscheint höchstens einmal in der Ausgabe.",
        "user_prompt_multi_coding_on": "\n\nBitte berücksichtige: Wenn auf eine Äußerung mehrere Codes passen, gib jede Zuordnung als eigenen Eintrag aus (gleicher 'Sprecher' und 'Impuls', anderer 'Shortcode') — höchstens zwei Codes pro Äußerung, den sichersten zuerst. Jeder Eintrag erhält als letztes Feld 'Konfidenz' (ganze Zahl 0-100, wie sicher der Code zutrifft); kalibriere über die volle Skala (90+ nur bei eindeutiger Textevidenz, 60–75 plausibel aber diskutabel, unter 50 spekulativ — kein pauschaler Standardwert; sehr kurze Äußerungen ohne eigenen Inhalt höchstens mittel) und nenne Kandidaten auch bei Unsicherheit, die Konfidenz macht das transparent. Achte besonders bei längeren Beiträgen darauf, ob mehrere distinkte Aspekte oder Themen angesprochen werden — falls ja, vergib pro Aspekt einen eigenen Code. Passt erkennbar kein Code, lass die Äußerung weg. Codiere das Transkript vollständig bis zur letzten Äußerung — keine vorzeitige Beendigung der Liste.",
        "user_prompt_multi_coding_off": "\n\nBitte berücksichtige: Pro Äußerung HÖCHSTENS EINEN Code aus dem Codebuch zuordnen — den passendsten. Wenn kein Code passt, lass die Äußerung weg. Eine Äußerung erscheint höchstens einmal in der Ausgabe.",
        "prompt_context": "\n\nWICHTIG: Codiere jeden Beitrag IM KONTEXT des Gesprächsverlaufs, nicht isoliert. Ob eine Äußerung eine Idee ausbaut, herausfordert, begründet oder eine Frage beantwortet, ergibt sich oft erst aus dem Bezug auf die vorangehenden Beiträge — beziehe deshalb bei jeder Code-Entscheidung die umliegenden Turns ein (z. B.: eine knappe Schülerantwort nach einer Warum-Frage ist eine Begründung; ein „Nein, aber …“ nach einem Vorschlag ist ein Herausfordern). Der Code gilt weiterhin pro Beitrag.",
        "user_prompt_context": "\n\nBitte berücksichtige: Jeder Beitrag wird im Licht des Gesprächsverlaufs codiert — lies vor jeder Code-Entscheidung die umliegenden Turns mit, denn die Funktion einer Äußerung (ausbauen, herausfordern, begründen, beantworten) zeigt sich oft erst im Bezug auf das Vorangegangene. Der Code wird trotzdem pro Beitrag vergeben.",
        "prompt_relevance": "\n\nWICHTIG: Nicht jeder Beitrag ist ein codierbarer Zug — unabhängig davon, welcher Code in Frage käme, bleiben UNCODIERT: (a) bloßes Drannehmen oder Aufrufen einer Person, also Beiträge, die nur aus einem Namen oder Sprecherlabel bestehen, auch mit Übergabe-Floskel („S2?“, „Okay. S10?“); (b) Beiträge, die AUSSCHLIESSLICH aus einer Quittung oder Minimal-Rückmeldung bestehen („Ja.“, „Genau.“, „Okay.“, „Mhm.“, „Achso.“); (c) unverständliche Passagen und Transkriptions-Platzhalter wie „(unv.)“. Für solche Beiträge gibst du GAR KEINEN Eintrag aus — auch keinen mit niedriger Konfidenz. Diese Regel geht der Anweisung vor, unsichere Kandidaten trotzdem zu nennen: ein Nicht-Zug wird nicht mit 0-20 % codiert, sondern weggelassen. ACHTUNG, häufiger Fehler: Die Regel greift NUR, wenn der GESAMTE Beitrag aus der Quittung besteht. Beginnt ein Beitrag mit „Ja“, „Genau“ oder „Okay“ und führt danach inhaltlich weiter, wird er GANZ NORMAL codiert — z. B. „Ja, das stimmt nicht so ganz mit den Ein-Euro-Jobs, die sind nämlich …“ ist ein vollwertiger Beitrag (hier: Herausfordern), ebenso „Genau. Das war also dieser Ursprung …“. AUSNAHME auch bei echten Kurzbeiträgen: Der Gesprächskontext macht sie eindeutig zu einem inhaltlichen Zug — etwa ein klares „Nein.“ als Widerspruch zu einem Vorschlag oder eine knappe Sachantwort auf eine Frage.",
        "user_prompt_relevance": "\n\nBitte beachte: Bloßes Drannehmen (Beitrag = nur Name/Label, ggf. mit Floskel), Beiträge die AUSSCHLIESSLICH aus einer Quittung bestehen („Ja.“, „Genau.“, „Okay.“, „Mhm.“) und Unverständliches („(unv.)“) bleiben uncodiert — dafür gibst du gar keinen Eintrag aus, auch keinen mit niedriger Konfidenz (Vorrang vor der Regel, unsichere Kandidaten zu nennen). WICHTIG: Beginnt ein Beitrag nur mit „Ja/Genau/Okay“ und geht danach inhaltlich weiter, wird er ganz normal codiert — die Regel gilt nur für Beiträge, die aus nichts anderem als der Quittung bestehen. Ausnahme: der Kontext macht einen echten Kurzbeitrag zum inhaltlichen Zug (Widerspruch, knappe Sachantwort).",
        "second_pass_prompt": "\n\nZWEITE PRÜFRUNDE: Die unten gelisteten Beiträge blieben in einem ersten Codier-Durchgang OHNE Code. Das vollständige Transkript liegt dir als Kontext vor — codiere aber AUSSCHLIESSLICH die gelisteten Beiträge und prüfe jeden im Licht des Gesprächsverlaufs noch einmal sorgfältig gegen das Codebuch. Es ist völlig legitim, dass Beiträge uncodiert bleiben (z. B. bloßes Drannehmen einer Person, reine Organisation) — vergib einen Code NUR, wenn er klar am Text und Kontext belegbar ist. Passende Codes gibst du im gewohnten Format aus; Beiträge ohne passenden Code lässt du weiterhin weg.\n\nZu prüfende Beiträge:\n{pending_list}",
        "second_pass_running": "Zweite Prüfrunde: {n} uncodierte(r) Beitrag/Beiträge werden noch einmal geprüft …",
        "second_pass_done": "Zweite Prüfrunde abgeschlossen: {n_new} zusätzliche Codierung(en) bei {n_checked} geprüften Beiträgen.",
        "button_analysis": "Analysieren",
        "button_cancel_analysis": "Abbrechen",
        "cancel_disabled_streaming_off": "Abbruch nur bei aktiviertem Streaming möglich (siehe Optionen).",
        "analysis_completed": "Analyse abgeschlossen",
        "download_report": "Report herunterladen",
        "import_session": "Sitzung importieren",
        "export_session": "Sitzung exportieren",
        "reset_session": "Sitzung zurücksetzen",
        "history_button": "Verlauf",
        "history_title": "Analyse-Verlauf",
        "history_save_now": "Aktuelle Sitzung in den Verlauf speichern",
        "history_load": "Laden",
        "history_delete": "Löschen",
        "history_empty": "Noch keine gespeicherten Sitzungen.",
        "history_select_label": "Gespeicherte Sitzung auswählen",
        "history_col_date": "Datum",
        "history_col_model": "Modell",
        "history_col_group": "Gruppe",
        "history_col_turns": "Beiträge",
        "history_saved_ok": "Im Verlauf gespeichert.",
        "history_loaded_ok": "Sitzung geladen.",
        "history_deleted_ok": "Eintrag gelöscht.",
        "history_save_blocked": "Bitte zuerst eine Analyse durchführen, bevor du sie speicherst.",
        "history_close": "Schließen",
        "tokens_aprox": "Input-Tokens: ca.",
        "cost_prediction": "Geschätzte Mindestkosten",
        "ollama_cloud_hint": "Hinweis: Ollama Cloud ist kostenlos und gut zum Testen mit kürzeren Transkripten und Codebüchern. Antwortzeiten schwanken stark je nach Serverlast. Für lange Transkripte oder ernsthafte Analysen empfehlen sich bezahlte Provider (OpenAI/Anthropic/Groq) oder lokales Ollama (\"ollama serve\").",
        "ollama_cloud_hint_label": "Cloud-Hinweis",
        "groq_quality_hint": "Hinweis: Groq ist sehr schnell und gut zum Testen. Die Ausgabequalität kann allerdings ungenau oder unzuverlässig sein. Für ernsthafte Analysen empfehlen sich OpenAI oder Anthropic.",
        "groq_quality_hint_label": "Qualitäts-Hinweis",
        "openrouter_hint": "OpenRouter ist ein Gateway-Service, der Anfragen an Drittanbieter (DeepSeek, Qwen, Mistral, etc.) weiterleitet. Empfohlen für günstige/kurze Test-Runs und Cross-Model-Vergleich; bei langen Transkripten + Reasoning-Modellen kann das Token-Budget pro Modell unterschiedlich knapp sein und Gateway-Latenz die UX dämpfen — für produktive lange Analysen lieber direkt den Original-Provider (OpenAI, Anthropic, …) nutzen. Daten gehen über OpenRouter und ggf. an den Underlying-Provider — datenschutzrechtlich genauer hinschauen, vor produktivem Einsatz im Schulkontext klären. Modellnamen-Format: 'provider/model' (z.B. 'deepseek/deepseek-v4-pro').",
        "openrouter_hint_label": "OpenRouter-Hinweis",
        "localmind_hint": "LocalMind ist ein EU-gehostetes (Österreich), OpenAI-kompatibles Inferenz-Gateway und der datenschutzfreundliche Standard: Transkripte verlassen die EU nicht. Ein einziger Key gibt Zugriff auf viele Modelle (eigene 'localmind-*'-Modelle sowie Llama, Mistral, Qwen, Gemma, DeepSeek u.a.). Die genauen Modell-Slugs sind ein Live-Katalog — im Optionen-Tab über 'LocalMind-Modelle laden' abrufen. Reasoning-Modelle verbrauchen Output-Budget für internes Chain-of-Thought; bei sehr langen Transkripten lieber ein Instruct-Modell.",
        "localmind_hint_label": "LocalMind-Hinweis",
        "custom_hint": "Eigener OpenAI-kompatibler Endpoint — Base-URL und API-Key werden im Optionen-Tab hinterlegt. Geeignet für selbst gehostete Server (vLLM, llama.cpp) oder institutionelle Gateways. Wo die Daten landen, hängt vom eingetragenen Endpoint ab — Datenschutz vor dem Einsatz mit echten Transkripten selbst prüfen.",
        "custom_hint_label": "Endpoint-Hinweis",
        "mistral_hint": "Mistral ist ein französisches Frontier-Model-Lab; die Chat-Completion-API wird in der EU gehostet (Paris / Frankfurt) und ist damit die naheliegende DSGVO-konforme Cloud-LLM-Wahl für Schul-Deployments, in denen US-Datenfluss problematisch ist. Starke Long-Context-Performance bei moderaten Kosten. Die 'magistral-*'-Modelle sind Reasoning-Modelle — sie verbrauchen Output-Budget für internes Chain-of-Thought; bei sehr langen Transkripten lieber 'mistral-large-latest' oder 'mistral-medium-latest'.",
        "mistral_hint_label": "Mistral-Hinweis",
        "deepseek_hint": "DeepSeek liefert Frontier-Class-Qualität zu einem Bruchteil der OpenAI-/Anthropic-Kosten (deepseek-chat ~ 0,27 $/1,10 $ pro 1M Tokens; deepseek-reasoner ~ 0,55 $/2,19 $) — diese Kostenkompression macht Multi-Coder-Reliabilitäts-Studien überhaupt erst finanzierbar. 'deepseek-reasoner' ist ein R1-Class-Reasoning-Modell; sein Chain-of-Thought ist zwar im Output ausgeblendet, verbraucht aber Token-Budget — bei langen Transkripten lieber 'deepseek-chat'. API wird von DeepSeek (CN) gehostet — datenschutzrechtlich vor Schul-Einsatz klären.",
        "deepseek_hint_label": "DeepSeek-Hinweis",
    },
    "analysis": {
        "tab_title": "Analyse",
        "llm_config_title": "LLM-Konfiguration",
        "general_info": "Allgemeine Informationen",
        "group_id": "ID der Gruppe",
        "num_pupils": "Gruppengröße",
        "name_teacher": "Name der Lehrperson im Transkript",
        "name_teacher_var": "LEHRER",
        "document_input": "Dokumenteneingabe",
        "upload_transcript": "Transkript hochladen",
        "upload_codebook": "Codebuch hochladen",
        "template_label": "Oder Vorlage verwenden:",
        "template_tseda_button": "T-SEDA-Codebuch laden",
        "template_tseda_hint": "Integriertes Codebuch für dialogische Unterrichtsgespräche (T-SEDA Collective 2023, University of Cambridge, CC BY) — setzt automatisch: Lehrkraft UND Schüler:innen codieren (kontextsensitiv), Mehrfach-Codierung mit Konfidenz.",
        "template_tseda_loaded": "T-SEDA-Codebuch geladen. Voreinstellungen aktiv: Lehrkraft und Schüler:innen codieren (im Gesprächskontext), bis zu 2 Codes pro Beitrag mit Konfidenz. Jetzt nur noch das Transkript hochladen.",
        "preview_codebook": "Vorschau Codebuch",
        "preview_transcript": "Vorschau Transkript",
        "placeholder": "Keine Datei ausgewählt",
        "browse": "Durchsuchen...",
        "placeholder_codebook": "Noch kein Codebuch hochgeladen...",
        "placeholder_transcript": "Noch kein Transkript hochgeladen...",
        "modal_restart_analysis": "Bitte Codebuch hochladen und Analyse erneut starten (ohne LLM)!",
        "modal_title_attention": "Hinweis",
        "modal_reset_session": "Möchten Sie die Sitzung wirklich zurücksetzen? Alle nicht gespeicherten Daten gehen verloren.",
        "modal_title_reset": "Sitzung zurücksetzen",
        "modal_title_error": "Fehler",
        "modal_confirm_reset": "Ja, zurücksetzen!",
        "modal_button_cancel": "Abbrechen",
        "modal_button_close": "Schließen",
        "cancelled_banner_title": "Analyse abgebrochen",
        "cancelled_banner_body": "{n} Impuls(e) wurden vor dem Abbruch codiert. Diese Teilergebnisse sind unvollständig und nicht als finale Codierung geeignet — bitte für endgültige Auswertungen die Analyse vollständig durchlaufen lassen.",
        "modal_upload_transcript_first": "Bitte zuerst ein Transkript hochladen!",
        "modal_upload_codebook_first": "Bitte zuerst ein Codebuch hochladen!",
        "teacher_not_found": "Lehrperson nicht im Transkript gefunden.",
        "check_format_tooltip": "Prüft das hochgeladene Transkript auf das erwartete Format (S01, S02, …). Weicht das Format ab (z.B. SPEAKER_00 mit Zeilenumbrüchen innerhalb eines Beitrags), wird eine konvertierte Version erstellt und zum Download angeboten. Die Dateiart (txt, docx) bleibt erhalten.",
        "format_status_valid": "Format gültig — keine Konvertierung nötig.",
        "format_status_invalid": "Format weicht ab — Wizard öffnen, um zu konvertieren.",
        "format_status_unsupported": "Dateityp wird nicht unterstützt — bitte .txt oder .docx (ohne Tabelle) verwenden.",
        "modal_title_format_check": "Transkript-Formatprüfung",
        "modal_format_already_valid": "Das Transkript liegt bereits im korrekten Format vor.",
        "modal_format_invalid_confirm": "Das Transkript entspricht nicht dem erwarteten Format. Eine konvertierte Version wurde erstellt. Vorschau der ersten Zeilen:",
        "modal_format_pdf_unsupported": "Die Formatkonvertierung wird für PDF-Dateien nicht unterstützt. Bitte laden Sie eine .txt- oder .docx-Datei hoch.",
        "modal_format_docx_table": "Diese .docx-Datei enthält eine Tabelle und kann nicht als Transkript konvertiert werden.",
        "download_converted": "Konvertiertes Transkript herunterladen",
        "format_modal_speakers_title": "Sprecher zuordnen",
        "format_modal_speakers_intro": "Folgende Sprecher wurden im Transkript erkannt. Bitte wählen Sie für jeden, wie er in der konvertierten Datei bezeichnet werden soll.",
        "format_modal_speakers_col_raw": "Erkannter Sprecher",
        "format_modal_speakers_col_target": "Zuordnung",
        "format_speaker_role_teacher": "Lehrperson",
        "format_speaker_role_student_n": "Schüler*in {n}",
        "format_speaker_role_ignore": "Ignorieren",
        "format_modal_brackets_title": "Aktionsbeschreibungen",
        "format_modal_brackets_intro": "Folgende Klammer-Annotationen wurden gefunden. Bitte entscheiden Sie, ob diese behalten oder entfernt werden sollen.",
        "format_bracket_keep": "Behalten",
        "format_bracket_strip": "Entfernen",
        "format_modal_preview_title": "Vorschau",
        "format_modal_button_next": "Weiter",
        "format_modal_button_back": "Zurück",
        "format_modal_button_convert": "Konvertieren",
        "format_modal_no_speakers": "Es konnten keine Sprecher automatisch erkannt werden. Das Transkript kann nicht konvertiert werden.",
        "format_bracket_samples": "Beispiele"
    },
    "noscribe": {
        "tab_title": "Transkription",
        "section_title": "Audio-Transkription (lokal)",
        "checking": "Engine wird geprüft …",
        "not_installed_intro": "Erzeuge Transkripte direkt aus Audioaufnahmen — vollständig lokal auf diesem Rechner, ohne dass die Aufnahme den Computer verlässt. Genutzt wird die quelloffene noScribe-Engine (Whisper + pyannote).",
        "bullet_local": "100 % lokal: Audio wird nie an einen Server gesendet.",
        "bullet_size": "Einmalige Installation lädt ca. 3 GB herunter (Engine + Whisper-Modell).",
        "bullet_gpl": "Nutzt das externe Open-Source-Projekt noScribe (GPL-3.0), das bei der Installation von GitHub geladen wird.",
        "windows_only": "Die automatische Installation der Engine ist in dieser Version nur unter Windows verfügbar.",
        "broken_note": "Eine frühere Installation wurde nicht abgeschlossen. Die Installation kann gefahrlos wiederholt werden — bereits geladene Teile werden weiterverwendet.",
        "install_button": "Transkriptions-Engine installieren",
        "repair_button": "Installation reparieren",
        "installing_title": "Engine wird installiert …",
        "ready_intro": "Audiodatei wählen, Optionen festlegen, dann transkribieren. Das fertige Transkript wird automatisch in den Analyse-Tab (Transkript-Feld) geladen.",
        "audio_label": "Audiodatei",
        "output_label": "Transkript speichern als",
        "output_placeholder": "Dateiname (ohne Endung)",
        "language_label": "Sprache",
        "language_auto": "Automatisch",
        "language_de": "Deutsch",
        "language_en": "Englisch",
        "model_label": "Modell",
        "model_needs_download": "{name} (lädt ~{gb} GB)",
        "speakers_label": "Sprecher:innen",
        "speakers_auto": "Automatisch",
        "speakers_none": "Keine",
        "speakers_hint_auto": "Tipp: Eine feste Sprecher:innen-Zahl verbessert die "
                              "automatische Sprechertrennung deutlich. „Automatisch\" "
                              "nur wählen, wenn die Anzahl wirklich unbekannt ist.",
        "speakers_hint_fixed": "Feste Sprecher:innen-Zahl gesetzt – das verbessert "
                               "die Sprechertrennung.",
        "pause_label": "Pausen markieren",
        "pause_none": "Keine",
        "start_time_label": "Start (hh:mm:ss)",
        "stop_time_label": "Stopp (hh:mm:ss)",
        "trim_label": "Zuschnitt (Wellenform)",
        "trim_hint": "Mit den Griffen Anfang und Ende festlegen — nur der markierte "
                     "Bereich wird transkribiert; die Start/Stopp-Felder werden automatisch gesetzt.",
        "trim_play": "Auswahl abspielen",
        "trim_pause": "Pause",
        "trim_reset": "Zurücksetzen",
        "trim_region": "Bereich",
        "trim_decoding": "Wellenform wird geladen …",
        "trim_failed": "Wellenform für dieses Format nicht verfügbar — Start/Stopp ggf. manuell eintragen.",
        "download_txt": "Transkript speichern (.txt)",
        "overlapping_label": "Überlappende Sprache",
        "disfluencies_label": "Füllwörter (äh, ähm …)",
        "timestamps_label": "Zeitmarken",
        "start_button": "Transkribieren",
        "running_title": "Transkription läuft …",
        "cancel_button": "Abbrechen",
        "step_of": "Schritt {n} von {total}",
        "progress_log_summary": "Details",
        "editor_title": "Transkript bearbeiten",
        "editor_hint": "Eine Zeile = ein Redebeitrag. Doppelklick auf eine Zelle, um die Sprecher:in (z. B. S01) oder den Text zu korrigieren. Mit „Übernehmen“ werden die Änderungen für die Analyse gespeichert und in die Transkript-Datei geschrieben.",
        "editor_placeholder": "Hier erscheint das Transkript nach der Transkription. Du kannst es auch manuell einfügen oder bearbeiten.",
        "editor_col_speaker": "Sprecher:in",
        "editor_col_text": "Äußerung",
        "editor_apply": "Übernehmen",
        "editor_apply_hint": "Speichert die Änderungen für die Analyse und in die Transkript-Datei.",
        "editor_applied": "Transkript für die Analyse übernommen.",
        "editor_applied_saved": "Übernommen — Analyse aktualisiert und in „{file}“ gespeichert.",
        "editor_edit_marker": "(Transkript manuell bearbeitet: {date})",
        "done_msg": "Transkript fertig — im Feld unten und im Analyse-Tab.",
        "desktop_detected": "Eine vorhandene noScribe-Desktop-Installation wurde erkannt und wird verwendet.",
        "engine_version": "Engine: noScribe {version}",
        "uninstall_button": "Engine deinstallieren",
        "uninstall_title": "Engine deinstallieren",
        "uninstall_confirm": "Die Transkriptions-Engine und das heruntergeladene Modell (ca. 3 GB) werden vollständig entfernt. Fortfahren?",
        "no_audio_selected": "Bitte zuerst eine Audiodatei auswählen.",
        "error_title": "Transkription fehlgeschlagen",
        "error_log_summary": "Technische Details anzeigen",
        "error_retry": "Erneut versuchen",
        "phase_preflight": "Voraussetzungen werden geprüft",
        "phase_uv": "Installer wird vorbereitet",
        "phase_python": "Python-Umgebung wird angelegt",
        "phase_noscribe": "noScribe wird geladen",
        "phase_deps": "Abhängigkeiten werden installiert (~2 GB)",
        "phase_model": "Whisper-Modell wird geladen (~0,8 GB)",
        "phase_health": "Installation wird überprüft",
        "phase_setup": "Audio wird vorbereitet",
        "phase_diarize": "Sprecher:innen werden erkannt",
        "phase_whisper_load": "Spracherkennung wird geladen",
        "phase_transcribe": "Transkription läuft",
        "phase_save": "Transkript wird gespeichert",
    },
    "consent": {
        # --- tab / form UI ---
        "tab_title": "Einwilligung",
        "section_title": "Einwilligungserklärung erzeugen",
        "intro_hint": "Erzeugen Sie eine druckfertige Einwilligungserklärung (DSGVO Art. 13) "
                      "für Lehrkräfte, die ihr eigenes Sprechverhalten analysieren lassen. "
                      "Felder anpassen, Vorschau erzeugen, als HTML herunterladen und ausdrucken.",
        "disclaimer": "Diese Vorlage ist eine Hilfestellung, keine Rechtsberatung. Bitte vor dem "
                      "Einsatz von Ihrer/Ihrem Datenschutzbeauftragten prüfen lassen und ggf. an "
                      "Ihr Bundesland/Ihre Einrichtung anpassen.",
        "field_project_name": "Bezeichnung der Fortbildung/des Projekts",
        "field_responsible": "Verantwortliche Stelle (Name, Einrichtung, Kontakt)",
        "field_dpo": "Datenschutzbeauftragte:r (optional)",
        "field_purpose": "Zweck der Verarbeitung",
        "field_legal_basis": "Rechtsgrundlage",
        "field_data_categories": "Datenkategorien",
        "field_llm_mode": "Analyse durch KI-Dienst",
        "field_llm_mode_cloud": "Cloud-Anbieter (z. B. OpenAI)",
        "field_llm_mode_local": "Lokal / EU (keine Drittlandübermittlung)",
        "field_llm_provider": "KI-Dienst (Name, Land)",
        "field_storage": "Speicherdauer",
        "field_revocation": "Kontakt für Widerruf",
        "field_authority": "Aufsichtsbehörde (optional)",
        "field_participant_name": "Name der Lehrkraft (optional, für die Ausgabe)",
        "field_place_date": "Ort, Datum (optional)",
        "per_participant_heading": "Pro Lehrkraft (optional)",
        "generate_button": "Vorschau erzeugen",
        "download_docx": "Als Word (.docx)",
        "download_pdf": "Als PDF",
        "pdf_failed": "PDF-Erzeugung fehlgeschlagen (Word erforderlich): {error}",
        "preview_empty": "Noch keine Vorschau. Felder ausfüllen und „Vorschau erzeugen“ klicken.",
        # --- prefilled defaults (generic, editable) ---
        "default_project_name": "Lehrkräftefortbildung – Analyse des eigenen Sprechverhaltens",
        "default_purpose": "Analyse des eigenen Sprech- und Gesprächsverhaltens zu Fortbildungs- "
                           "und Reflexionszwecken.",
        "default_legal_basis": "Einwilligung (Art. 6 Abs. 1 lit. a DSGVO)",
        "default_data_categories": "Audioaufnahme Ihrer eigenen Stimme sowie das daraus "
                                   "automatisch erzeugte Transkript.",
        "default_storage": "bis zum Abschluss der Fortbildung",
        # --- placeholders (institution-specific, must be filled) ---
        "ph_responsible": "z. B. TU Dortmund, Institut …, Prof. … , Anschrift, E-Mail",
        "ph_dpo": "Name und Kontakt der/des Datenschutzbeauftragten",
        "ph_revocation": "z. B. Funktions-E-Mail des Fortbildungsteams",
        "ph_authority": "z. B. Landesbeauftragte für Datenschutz NRW, Kontakt",
        "ph_participant_name": "Vor- und Nachname",
        "ph_place_date": "z. B. Dortmund, 10.06.2026",
        "ph_llm_provider": "z. B. OpenAI, USA",
        # --- 'field missing' inline warnings on the document ---
        "missing_responsible": "Verantwortliche Stelle fehlt",
        "missing_purpose": "Zweck fehlt",
        "missing_legal_basis": "Rechtsgrundlage fehlt",
        "missing_data_categories": "Datenkategorien fehlen",
        "missing_storage": "Speicherdauer fehlt",
        "missing_revocation": "Widerrufs-Kontakt fehlt",
        # --- generated document ---
        "doc_lang": "de",
        "doc_title": "Einwilligungserklärung",
        "doc_project_generic": "dieser Fortbildung",
        "doc_provider_generic": "dem konfigurierten KI-Dienst",
        "doc_purpose_generic": "dem oben genannten Zweck",
        "doc_part1_heading": "Studieninformation",
        "doc_part2_heading": "Informationspflichten zum Datenschutz (Art. 13 DSGVO)",
        "doc_part3_heading": "Einwilligungserklärung",
        "doc_intro": "Im Rahmen von {project} analysieren wir Ihr eigenes sprachliches Handeln, "
                     "um Ihnen ein Feedback zu Ihrem Sprech- und Gesprächsverhalten zu geben. "
                     "Dazu wird eine Audioaufnahme Ihrer eigenen Äußerungen angefertigt.",
        "doc_pipeline": "Die Aufnahme wird zunächst direkt auf dem Gerät transkribiert "
                        "(Spracherkennung); die Audiodatei verlässt das Gerät dabei nicht. "
                        "Anschließend wird das Transkript (Text) für die Analyse ausgewertet.",
        "doc_art13_intro": "Wir verarbeiten Ihre Daten gemäß den Vorschriften der "
                           "Datenschutz-Grundverordnung (DSGVO). Mit den folgenden Hinweisen kommen "
                           "wir unserer Informationspflicht nach Artikel 13 DSGVO nach.",
        "doc_responsible_label": "Verantwortliche Stelle",
        "doc_dpo_label": "Datenschutzbeauftragte:r",
        "doc_purpose_label": "Zweck der Verarbeitung",
        "doc_legal_basis_label": "Rechtsgrundlage",
        "doc_data_categories_label": "Datenkategorien",
        "doc_recipients_label": "Empfänger der Daten",
        "doc_transcription_note": "Transkription: Die Spracherkennung läuft lokal auf dem "
                                  "verwendeten Gerät. Die Audioaufnahme wird nicht an Dritte übermittelt.",
        "doc_recipients_cloud": "Analyse: Für die Auswertung wird der Transkript-Text an den "
                                "folgenden Dienst übermittelt: {provider}. Sofern dieser Anbieter "
                                "außerhalb der EU/des EWR verarbeitet, handelt es sich um eine "
                                "Übermittlung in ein Drittland; ein der EU gleichwertiges "
                                "Datenschutzniveau kann dort nicht in jedem Fall gewährleistet werden.",
        "doc_recipients_local": "Analyse: Die Auswertung des Transkripts erfolgt lokal bzw. auf "
                                "einem Dienst innerhalb der EU/des EWR. Eine Übermittlung in ein "
                                "Drittland findet nicht statt.",
        "doc_storage_label": "Speicherung",
        "doc_storage_sentence": "Wir speichern Ihre personenbezogenen Daten {duration}. Anschließend "
                                "werden die Daten gelöscht oder anonymisiert.",
        "doc_rights_label": "Ihre Betroffenenrechte",
        "right_withdraw": "Widerrufsrecht: Sie haben das Recht, Ihre Einwilligung jederzeit mit "
                          "Wirkung für die Zukunft zu widerrufen.",
        "right_access": "Auskunftsrecht: Sie haben das Recht zu erfahren, welche personenbezogenen "
                        "Daten von Ihnen verarbeitet werden.",
        "right_rectify": "Recht auf Berichtigung: Sie haben das Recht, falsche personenbezogene "
                         "Daten berichtigen zu lassen.",
        "right_erase": "Recht auf Löschung: Sie können jederzeit die Löschung Ihrer Daten verlangen.",
        "right_restrict": "Recht auf Einschränkung der Verarbeitung: Sie können die Einschränkung "
                          "der Verarbeitung verlangen.",
        "right_portability": "Recht auf Datenübertragbarkeit: Sie haben das Recht, die Sie "
                             "betreffenden personenbezogenen Daten in einem strukturierten, gängigen "
                             "und maschinenlesbaren Format zu erhalten.",
        "right_object": "Widerspruchsrecht: Sie können jederzeit gegen die Verarbeitung der Sie "
                        "betreffenden Daten Widerspruch einlegen.",
        "right_complaint": "Beschwerderecht bei einer Aufsichtsbehörde: Wenn Sie der Auffassung sind, "
                           "dass bei der Verarbeitung Ihrer Daten datenschutzrechtliche Vorschriften "
                           "nicht beachtet wurden, können Sie sich an die zuständige Aufsichtsbehörde wenden.",
        "doc_rights_contact": "Zur Geltendmachung Ihrer Rechte wenden Sie sich bitte an: {responsible}",
        "doc_revocation_sentence": "Ihren Widerruf richten Sie bitte an: {revocation}",
        "doc_authority_label": "Aufsichtsbehörde",
        "doc_voluntary": "Mir ist bewusst, dass meine Teilnahme freiwillig ist und ich bei einer "
                         "Verweigerung meiner Einwilligung keinerlei Nachteile erleide. Meine "
                         "Einwilligung kann ich jederzeit mit Wirkung für die Zukunft widerrufen. "
                         "Für einen Widerruf der Einwilligung bedarf es keiner Begründung und es "
                         "entstehen daraus keinerlei Nachteile. Im Fall eines Widerrufs werden meine "
                         "personenbezogenen Daten unmittelbar gelöscht. Durch den Widerruf der "
                         "Einwilligung wird die Rechtmäßigkeit der aufgrund der Einwilligung bis zum "
                         "Widerruf erfolgten Verarbeitung nicht berührt.",
        "doc_consent_main": "Ich willige ein, dass meine Audioaufnahme und das daraus erzeugte "
                            "Transkript zu folgendem Zweck verarbeitet werden: {purpose}",
        "doc_consent_cloud": "Ich willige ein, dass der Transkript-Text zur Analyse an {provider} "
                             "übermittelt wird (ggf. Drittlandübermittlung, siehe oben).",
        "doc_consent_participate": "Hiermit willige ich ein, an {project} teilzunehmen.",
        "doc_yes": "Ja",
        "doc_no": "Nein",
        "doc_name_line": "Vor- und Nachname in Druckschrift",
        "doc_signature_line": "Ort, Datum, Unterschrift",
        "doc_footer": "Vorlage auf Basis des CC0-lizenzierten Consent-Gen-RDMO (TU Dortmund). Diese "
                      "Erklärung ist eine Hilfestellung und keine Rechtsberatung — bitte vor dem "
                      "Einsatz von Ihrer/Ihrem Datenschutzbeauftragten prüfen lassen.",
    },
    "results": {
        "tab_title": "Ergebnisse",
        "no_results": "Bitte zuerst eine Analyse durchführen!",
        "no_results_title": "Noch keine Ergebnisse",
        "autopilot_chooser_title": "Welche Codierung anzeigen?",
        "autopilot_chooser_intro": "Der Autopilot hat zwei Codierungen erstellt. Welche möchtest du im Ergebnis-Tab anzeigen?",
        "no_data": "Noch keine Daten vorhanden",
        "section_quantitative_analysis": "Quantitative Verteilung der Gesprächsanteile",
        "class_size": "Klassengröße",
        "num_participants": "Anzahl beteiligter Schüler:innen",
        "participation_rate": "Beteiligungsquote",
        "distribution_of_turns": "Gesprächsverteilung",
        "interaction_turns": "Gesprächsbeiträge",
        "teacher": "Lehrperson",
        "students": "Schüler:innen",
        "turn_count": "Anzahl Beiträge",
        "turn_length": "Länge in Wörtern M (SD)",
        "teacher_turns_box": "Beiträge Lehrkraft",
        "pupils_turns_box": "Beiträge Schüler:innen",
        "longest_teacher_turn": "Längster Lehrkraft-Beitrag",
        "short_answers_share": "Kurzantworten (≤3 Wörter)",
        "avg_words_subtitle": "Ø {n} Wörter",
        "words_unit": "Wörter",
        "section_qualitative_analysis": "Qualitative Analyse",
        "impulses_count": "Anzahl der Redezüge",
        "coded_impulses": "Codierte Gesprächsimpulse",
        "most_frequent_codes": "Häufigste Codes",
        "teacher_talking_rate": "Redeanteil (Lehrperson / Schüler:innen)",
        "impulses_distribution": "Verteilung der Gesprächsimpulse",
        "impulses_coding": "Codierung der Gesprächsimpulse",
        "results_group": "Ergebnisse Gruppe",
        "words_total": "Wörter insgesamt",
        "quantity": "Anzahl",
        "speaker": "Sprecher:in",
        "caption": "Legende",
        "section": "Abschnitt",
        "share": "Anteil",
        "section_first": "Erstes Drittel",
        "section_middle": "Mittleres Drittel",
        "section_last": "Letztes Drittel",
        "over_time_quant_title": "Beteiligung im Verlauf",
        "over_time_quali_title": "Code-Verteilung im Verlauf",
        "methods_title": "Methodentext für Paper",
        "methods_intro": "Auto-generierter Absatz für den Methodenteil eines Manuskripts. Du kannst den Text vor dem Kopieren noch anpassen.",
        "methods_copy": "In die Zwischenablage kopieren",
        "methods_copied": "Methodentext kopiert",
        "methods_copy_failed": "Kopieren fehlgeschlagen — bitte den Text manuell markieren.",
        "transitions_title": "Code-Übergänge",
        "transitions_intro": "Wahrscheinlichkeit, mit der ein Code (Zeile) auf den nächsten Code (Spalte) folgt. Nur aufeinanderfolgende codierte Beiträge zählen; nicht-codierte Beiträge werden übersprungen. Bei Mehrfach-Codierung wird der erste (priorisierte) Code pro Beitrag verwendet.",
        "transitions_n_pairs": "Übergänge",
        "transitions_no_data": "Mindestens zwei aufeinanderfolgende codierte Beiträge nötig.",
        "edit_code_hint": "Doppelklick auf die Shortcode-Spalte, um einen Code zu korrigieren.",
        "edit_code_invalid": "'{code}' ist kein gültiger Code. Gültige Codes: {valid}",
    },
    "options": {
        "tab_title": "Optionen",
        "keyring_unavailable": "Kein System-Keyring verfügbar — der API-Schlüssel wird nur für diese Sitzung gespeichert.",
        "api_configuration": "API-Konfiguration",
        "api_select_title": "API-Auswahl",
        "api_select": "OpenAI nutzen",
        "api_groq_found": "API-Key für Groq vorhanden",
        "api_groq_not_found": "Kein API-Key für Groq vorhanden. Bitte konfigurieren.",
        "api_openai_found": "API-Key für openAI vorhanden",
        "api_openai_not_found": "Kein API-Key für openAI vorhanden. Bitte konfigurieren.",
        "api_anthropic_found": "API-Key für Anthropic vorhanden",
        "api_anthropic_not_found": "Kein API-Key für Anthropic vorhanden. Bitte konfigurieren.",
        "api_ollama_found": "Ollama Cloud-API-Key vorhanden",
        "api_ollama_not_found": "Kein Cloud-API-Key — lokales Ollama wird verwendet (localhost)",
        "api_openrouter_found": "API-Key für OpenRouter vorhanden",
        "api_openrouter_not_found": "Kein API-Key für OpenRouter vorhanden. Bitte konfigurieren.",
        "api_mistral_found": "API-Key für Mistral vorhanden",
        "api_mistral_not_found": "Kein API-Key für Mistral vorhanden. Bitte konfigurieren.",
        "api_deepseek_found": "API-Key für DeepSeek vorhanden",
        "api_deepseek_not_found": "Kein API-Key für DeepSeek vorhanden. Bitte konfigurieren.",
        "api_localmind_found": "API-Key für LocalMind vorhanden",
        "api_localmind_not_found": "Kein API-Key für LocalMind vorhanden. Bitte konfigurieren.",
        "api_custom_found": "API-Key für den eigenen Endpoint vorhanden",
        "api_custom_not_found": "Kein API-Key für den eigenen Endpoint vorhanden. Bitte konfigurieren.",
        "provider_custom_label": "Eigener Endpoint (OpenAI-kompatibel)",
        "custom_base_url_label": "Base-URL",
        "custom_base_url_hint": "OpenAI-kompatibler Endpoint, z.B. https://host.example/v1 — etwa ein eigener vLLM-Server oder ein institutionelles Gateway. Der passende API-Key wird rechts wie gewohnt gespeichert (OS-Keyring).",
        "custom_base_url_missing": "Bitte zuerst eine Base-URL für den eigenen Endpoint eintragen.",
        "add_provider_button": "Anbieter hinzufügen",
        "add_provider_title": "Eigenen Anbieter hinzufügen",
        "edit_provider_button": "Bearbeiten",
        "edit_provider_title": "Anbieter bearbeiten",
        "delete_provider_button": "Anbieter löschen",
        "delete_provider_title": "Anbieter löschen",
        "delete_provider_warning": "Anbieter „{name}“ wirklich löschen? Die zugehörige Modell-Liste und der gespeicherte API-Key werden entfernt.",
        "provider_name_label": "Name",
        "provider_name_placeholder": "z.B. Uni-vLLM",
        "provider_incomplete": "Bitte Name und Base-URL angeben.",
        "provider_added": "Anbieter „{name}“ hinzugefügt. Jetzt den API-Key speichern und Modelle laden.",
        "provider_updated": "Anbieter aktualisiert.",
        "provider_deleted": "Anbieter gelöscht.",
        "fetch_models_button": "Modelle vom Anbieter laden",
        "fetch_models_hint": "Ruft die aktuelle Modell-Liste des gewählten Anbieters ab und aktualisiert die Registry. Preise bereits eingetragener Modelle bleiben erhalten; neue Modelle starten mit 0.",
        "fetch_models_no_key": "Zum Laden der Modell-Liste zuerst einen API-Key für diesen Anbieter speichern.",
        "fetch_models_empty": "Keine Modelle vom Anbieter erhalten.",
        "fetch_models_success": "{n} Modelle geladen.",
        "fetch_models_error": "Modelle konnten nicht geladen werden: {error}",
        "ollama_running": "Ollama läuft unter {url}",
        "ollama_not_running": "Ollama nicht erreichbar unter {url}",
        "ollama_start_button": "Ollama starten",
        "ollama_start_error": "Ollama konnte nicht gestartet werden. Ist es installiert?",
        "error_title": "Fehler",
        "no_api_key_warning": "Kein API-Key gefunden. Bitte einen API-Key konfigurieren, um LLM-Funktionen zu nutzen.",
        "button_change": "Ändern",
        "add_api_key_placeholder": "API-Key eingeben",
        "add_api_key_save": "Speichern",
        "add_api_key_title": "API-Key ändern",
        "button_delete": "Löschen",
        "delete_api_key_warning": "Möchten Sie den API-Key wirklich löschen?",
        "delete_api_key_confirm": "Ja, löschen!",
        "delete_api_key_title": "API-Key löschen",
        "button_reset": "Zurücksetzen",
        "llm_models": "Modelle für LLM-Auswahl",
        "available_models": "Verfügbare Modelle",
        "add_model": "Modell hinzufügen",
        "model_id": "Modell-ID",
        "model_provider": "Modell-Anbieter",
        "input_cost": "Kosten pro 1M Input-Tokens (€)",
        "output_cost": "Kosten pro 1M Output-Tokens (€)",
        "cost_placeholder": "z.B., 0.40",
        "add_model_placeholder": "z.B., gpt-4o",
        "modal_button_add": "Hinzufügen",
        "add_model_title": "Ein Modell hinzufügen",
        "model_is_local": "Modell läuft lokal (datenschutzkonform)",
        "model_is_local_hint": "Nur ankreuzen, wenn das Modell wirklich auf diesem Rechner ausgeführt wird (z.B. lokales Ollama). Cloud-Endpunkte wie „Ollama Cloud\" oder OpenAI bitte ungeprüft lassen — sonst werden sie im „Nur lokal\"-Modus fälschlich zugelassen.",
        "remove_model": "Modell entfernen",
        "modal_remove_model_warning": "Möchten Sie die ausgewählten Modelle wirklich entfernen? Dieser Vorgang kann nicht rückgängig gemacht werden.",
        "modal_remove_confirm": "Ja, entfernen!",
        "modal_remove_title": "Modelle entfernen",
        "reset_model_selection_confirm": "Möchten Sie die Modellauswahl wirklich auf den Standard zurücksetzen?",
        "reset_model_selection_title": "Modellauswahl zurücksetzen",
        "modal_model_reset_confirm": "Ja, zurücksetzen!",
        "custom_prompts": "Benutzerdefinierte Prompts",
        "system_prompt_label": "System-Prompt",
        "user_prompt_label": "User-Prompt",
        "change_system_prompt": "System-Prompt ändern",
        "reset_system_prompt_title": "System-Prompt zurücksetzen",
        "reset_system_prompt_confirm": "Möchten Sie den System-Prompt wirklich zurücksetzen?",
        "change_user_prompt": "User-Prompt ändern",
        "reset_user_prompt_title": "User-Prompt zurücksetzen",
        "reset_user_prompt_confirm": "Möchten Sie den User-Prompt wirklich zurücksetzen?",
        "additional_options": "Weitere Optionen",
        "teacher_name": "Name der Lehrperson",
        "group_id": "ID der Gruppe",
        "num_students": "Gruppengröße",
        "reset_group_parameters_title": "Gruppenparameter zurücksetzen",
        "reset_group_parameters_confirm": "Möchten Sie die Gruppenparameter wirklich zurücksetzen?",
        "advanced_options": "Erweitert",
        "streaming_switch": "Progressive Anzeige (Streaming)",
        "streaming_switch_help": "Wenn aktiv, werden Codierungen schon während der LLM-Antwort angezeigt, statt erst am Ende. Funktioniert für OpenAI, Anthropic, Groq und Ollama. Standard: an.",
        "streaming_switch_cancel_warning": "Bei deaktiviertem Streaming kann eine laufende Analyse nicht abgebrochen werden — der Provider-Call läuft als ein einziger blockierender Request.",
        "local_only_switch": "Nur lokal (Ollama)",
        "local_only_switch_help": "Wenn aktiv, sind alle Cloud-Anbieter (OpenAI, Anthropic, Groq) ausgeblendet — nur lokales Ollama wird zugelassen. Sinnvoll für Schulen mit strengen Datenschutz-Vorgaben. Standard: aus.",
        "cost_tracker_header": "Kosten-Tracker (kumuliert)",
        "cost_tracker_empty": "Noch keine kostenpflichtigen Analysen aufgezeichnet.",
        "cost_tracker_total": "Summe",
        "cost_tracker_col_provider": "Anbieter",
        "cost_tracker_col_model": "Modell",
        "cost_tracker_col_cost": "Kosten",
        "cost_tracker_col_runs": "Analysen",
        "cost_tracker_reset": "Tracker zurücksetzen",
        "cost_tracker_reset_title": "Kosten-Tracker zurücksetzen",
        "cost_tracker_reset_confirm": "Möchten Sie den kumulierten Kosten-Verlauf wirklich löschen? Dieser Vorgang kann nicht rückgängig gemacht werden.",
        "self_test_header": "Selbsttest (App testen)",
        "self_test_intro": "Führt deterministische Prüfungen gegen ein bekanntes Demo-Transkript aus — keine LLM-Aufrufe, keine Kosten. Bestätigt, dass Beteiligungs-Zählungen, Beitrags-Statistiken, Intercoder-Maße und Reproduzierbarkeits-Hash korrekt rechnen.",
        "self_test_run": "App testen",
        "self_test_all_pass": "Alle {n} Prüfungen bestanden — die App rechnet wie erwartet.",
        "self_test_some_fail": "Nur {passed} von {total} Prüfungen bestanden. Bitte Issue auf GitHub melden.",
        "self_test_col_check": "Prüfung",
        "self_test_col_expected": "Erwartet",
        "self_test_col_actual": "Tatsächlich",
    },
    "feedback": {
        "tab_title": "Feedback",
        "section_title": "Unterrichts-Feedback",
        "intro_hint": "Erzeuge ein wissenschaftlich fundiertes, formatives Feedback zur "
                      "analysierten Stunde — auf Basis des T-SEDA-Profils der Gesprächs-Moves "
                      "der Lehrkraft und der quantitativen Redekennzahlen. Text prüfen, "
                      "bearbeiten und exportieren.",
        "disclaimer": "Dieses Feedback ist eine Reflexionshilfe, keine Bewertung oder Note. "
                      "Es wird von einem Sprachmodell aus den Analyse-Daten erzeugt — bitte "
                      "kritisch prüfen.",
        "empty_state": "Bitte zuerst eine Analyse mit LLM-Codierung durchführen (Tab "
                       "„Analyse“) — oder unten einen bereits exportierten Report "
                       "hochladen. Das Feedback wird aus der Codierung und den "
                       "Redekennzahlen erzeugt.",
        "upload_label": "Report hochladen (optional)",
        "upload_button": "Datei wählen",
        "upload_placeholder": "Keine Datei ausgewählt",
        "upload_hint": "Exportierten Report einlesen — etwa nachdem du die Codierungen "
                       "in Word oder Excel geprüft und korrigiert hast. Das Feedback "
                       "beruht dann auf deiner geprüften Fassung statt auf der Roh-"
                       "Ausgabe des Modells. Unterstützt: DOCX, XLSX, CSV/ZIP, HTML. "
                       "Kennzahlen und Codes werden aus dem Dokument gelesen, eine "
                       "laufende Analyse ist nicht nötig.",
        "import_ok": "Report eingelesen: {turns} Beiträge, davon {coded} codiert.",
        "import_active": "Feedback nutzt den hochgeladenen Report ({turns} Beiträge, "
                         "{coded} codiert) statt der Analyse in dieser Sitzung.",
        "import_teacher_label": "Als Lehrkraft wird „{label}“ gezählt (aus dem Report "
                                "übernommen).",
        "import_clear": "Verwerfen",
        "import_cleared": "Hochgeladener Report verworfen.",
        "import_no_codebook": "Kein Codebuch geladen — das Modell kennt dann nur die "
                              "Kürzel, nicht ihre Bedeutung. Für ein aussagekräftiges "
                              "Feedback im Tab „Analyse“ ein Codebuch laden (die "
                              "T-SEDA-Vorlage genügt).",
        "import_unsupported_format": "Dieses Dateiformat wird nicht unterstützt. Möglich "
                                     "sind DOCX, XLSX, CSV/ZIP und HTML — PDF nicht, da "
                                     "sich daraus die Tabellenstruktur nicht sicher "
                                     "rekonstruieren lässt.",
        "import_unreadable": "Die Datei ließ sich nicht lesen. Ist es ein unveränderter "
                             "TalkTrace-Report?",
        "import_no_table": "In der Datei wurde keine Codierungs-Tabelle gefunden. Sie "
                           "braucht die Spalten für Äußerung und Shortcode — beim Export "
                           "muss der Abschnitt „Qualitative Codierung“ aktiviert sein.",
        "xlsx_unavailable": "Für XLSX-Dateien fehlt das Paket openpyxl. Bitte ein "
                            "anderes Format wählen.",
        "generate_button": "Feedback erzeugen",
        "regenerate_button": "Neu erzeugen",
        "generating": "Feedback wird erzeugt…",
        "editor_label": "Feedback (bearbeitbar)",
        "editor_hint": "Der Text kann vor dem Export bearbeitet werden.",
        "preview_empty": "Noch kein Feedback erzeugt.",
        "copy": "Kopieren",
        "download_docx": "Als Word (.docx)",
        "download_pdf": "Als PDF",
        "pdf_failed": "PDF-Export fehlgeschlagen: {error}",
        "pdf_unavailable_linux": "Der PDF-Export benötigt Microsoft Word und ist unter "
                                 "Linux nicht verfügbar. Bitte den Word-Download (.docx) "
                                 "verwenden.",
        "feedback_empty": "Das Modell hat kein Feedback zurückgegeben. Bitte erneut "
                          "versuchen oder ein anderes Modell wählen.",
        "feedback_failed": "Feedback-Erzeugung fehlgeschlagen: {error}",
        "no_key": "Für den gewählten Anbieter ist kein API-Schlüssel hinterlegt. Bitte "
                  "im Tab „Optionen“ eintragen.",
        "llm_hint": "Das Feedback wird mit diesem Modell erzeugt — vorausgewählt ist "
                    "die Auswahl aus dem Analyse-Tab, hier änderbar (z.B. ein "
                    "günstigeres Modell als für die Codierung).",
        "doc_title": "Unterrichts-Feedback",
        "cost_estimate": "Geschätzte Kosten: {cost} €",
    },
    "info": {
        "tab_title": "Info / Lizenz",
        "dev_heading": "Entwicklung",
        "dev_current": "Aktuelle Version",
        "dev_origin": "Ursprungsversion",
        "license_heading": "Lizenz",
        "license_text": "Dieses Projekt steht unter der **GNU Affero General Public License v3.0** (AGPL-3.0). Nutzung, Weitergabe und Bearbeitung — auch zu kommerziellen Zwecken — sind erlaubt, aber jede Weitergabe oder Bereitstellung als Online-Dienst muss den vollständigen entsprechenden Quellcode unter derselben Lizenz mitliefern. Beim Weitergeben sind Lizenztext und NOTICE-Datei mitzuführen, geänderte Dateien sind als geändert zu kennzeichnen.",
        "transcription_heading": "Audio-Transkription (optionales Modul)",
        "transcription_text": "Der Tab **Transkription** erzeugt Transkripte direkt aus Audioaufnahmen — **vollständig lokal auf deinem Rechner**. Die Audiodatei wird zu keinem Zeitpunkt an einen Server übertragen; das ist der entscheidende Datenschutz-Vorteil gegenüber Cloud-Transkriptionsdiensten.\n\nDie Transkription nutzt das eigenständige Open-Source-Projekt [noScribe](https://github.com/kaixxx/noScribe) von Kai Dröge (Whisper-Spracherkennung + pyannote-Sprechertrennung), das unter der **GPL-3.0** steht. noScribe wird auf deinen Wunsch hin einmalig von GitHub heruntergeladen und ausschließlich als **separater Subprozess** aufgerufen — TalkTrace bindet, importiert oder bündelt keinen noScribe-Code. Dadurch bleiben beide Projekte lizenzrechtlich sauber getrennt (TalkTrace: AGPL-3.0 · noScribe: GPL-3.0). Die Whisper-Modelle sowie die pyannote-Modelle werden aus den jeweiligen öffentlichen Quellen geladen; Einzelheiten siehe NOTICE.",
        "consent_heading": "Einwilligungserklärung (optionales Modul)",
        "consent_text": "Der Tab **Einwilligung** erzeugt eine druckfertige Einwilligungserklärung nach **DSGVO Art. 13** für den Fortbildungskontext — gedacht für den Fall, dass ein Fortbildungsteam *mit* Lehrkräften arbeitet und jede Lehrkraft in die Verarbeitung ihrer **eigenen** Aufnahme einwilligt. Das Formular ist vorausgefüllt, die Vorschau wird live angezeigt und als **Word (.docx)** oder **PDF** exportiert.\n\nDie Erklärung bildet den tatsächlichen Datenfluss ab: **lokale Transkription** (Audio verlässt das Gerät nicht) gegenüber dem konfigurierten **KI-Dienst als Empfänger** bzw. einer möglichen **Drittlandübermittlung**. Der Wortlaut ist vom **CC0**-lizenzierten [Consent-Gen-RDMO](https://github.com/berndzey/Consent-Gen-RDMO) der TU Dortmund (Bernd Zey, Wibke Kleina) adaptiert.\n\n⚠️ Die erzeugte Erklärung ist eine **Hilfestellung, keine Rechtsberatung**. Bitte vor dem Einsatz von der/dem Datenschutzbeauftragten prüfen und an die Gegebenheiten des Bundeslands/der Einrichtung anpassen lassen.",
    },
    "report": {
        "header": "Gesprächsanalyse – Gruppe",
        "model_used": "Verwendetes LLM-Modell",
        "section_1": "1. Quantitative Verteilung der Gesprächsanteile",
        "class_size": "Klassengröße",
        "pupil_count": "Anzahl beteiligter Schüler:innen",
        "participation_rate": "Beteiligungsquote",
        "table": "Tabelle",
        "interaction_turns_teacher_pupils": "Gesprächsbeiträge der Lehrperson und der Schüler:innen",
        "participants": "Teilnehmende",
        "teacher": "Lehrperson",
        "pupils": "Schüler:innen",
        "quantity": "Anzahl",
        "length_words": "Länge in Wörtern",
        "interaction_turns": "Gesprächsbeiträge",
        "figure": "Abbildung",
        "distribution_of_turns": "Gesprächsverteilung",
        "section_2": "2. Qualitative Codierung der Gesprächsbeiträge",
        "impulses_count": "Anzahl der codierten Beiträge",
        "teacher_impulses": "Codierte sprachliche Beiträge",
        "teacher_statement": "Äußerung (kurz)",
        "speaker": "Sprecher:in",
        "code": "Code",
        "shortcode": "Shortcode",
        "code_by_speaker": "Code-Verteilung nach Sprechergruppe",
        "total": "Gesamt",
        "confidence_legend": "Konfidenz der LLM-Codierung",
        "confidence_high": "sicher",
        "confidence_low": "sehr unsicher",
        "caption": "Legende",
        "fingerprint": "Reproduzierbarkeits-Hash",
        "methods_section": "Methodentext"
    },
    "system_prompts": {
        "no_code": "Kein Code verwendet",
        "analysis_running": "Die Analyse läuft.",
        "wait": "Dies kann eine Weile dauern...",
        "waiting_LLM": "Warten auf Antwort des LLM...",
        "calculating": "Berechne...",
        "error": "Fehler bei LLM-Analyse",
        "try_again": "Bitte versuchen Sie es erneut!"
    },
    "stats": {
        "students": "Schüler:innen",
        "teacher": "Lehrer:in"
    },
    "testing": {
        "tab_title": "Testen",
        "section_header": "Codebook-Validierung durch Intercoder-Übereinstimmung",
        "intro": "Laden Sie zwei TalkTrace-Reports (.docx, .xlsx oder .html) hoch, die aus demselben Transkript mit unterschiedlichen Modellen erzeugt wurden. Die Impulse werden per Äußerungstext abgeglichen; Cohen's Kappa wird über die zugewiesenen Codes berechnet. Impulse, die nur einer der beiden Reports codiert hat, fließen als Kategorie „unkodiert“ ein.",
        "upload_report_a": "Report A (.docx / .xlsx / .html)",
        "upload_report_b": "Report B (.docx / .xlsx / .html)",
        "placeholder_report": "Noch kein Report hochgeladen...",
        "summary_header": "Überblick",
        "summary_n_pairs": "Abgeglichene Paare",
        "summary_n_both": "Von beiden codiert",
        "summary_only_a": "Nur in A",
        "summary_only_b": "Nur in B",
        "summary_percent_agreement": "Prozentuale Übereinstimmung",
        "summary_krippendorff": "Krippendorff's α",
        "summary_gwet_ac1": "Gwet's AC1",
        "summary_brennan_prediger": "Brennan-Prediger κ",
        "kappa_header": "Cohen's Kappa",
        "kappa_ci_label": "95%-KI",
        "per_code_header": "Übereinstimmung pro Code",
        "per_code_col_code": "Code",
        "per_code_col_n_a": "n (A)",
        "per_code_col_n_b": "n (B)",
        "per_code_col_f1": "F1",
        "per_code_col_precision": "Präzision",
        "per_code_col_recall": "Trefferquote",
        "kappa_not_ready": "Bitte beide Reports hochladen, um Kappa zu berechnen.",
        "kappa_interpretation_poor": "Keine Übereinstimmung",
        "kappa_interpretation_slight": "Geringe Übereinstimmung",
        "kappa_interpretation_fair": "Ausreichende Übereinstimmung",
        "kappa_interpretation_moderate": "Moderate Übereinstimmung",
        "kappa_interpretation_substantial": "Beträchtliche Übereinstimmung",
        "kappa_interpretation_almost_perfect": "Fast perfekte Übereinstimmung",
        "confusion_header": "Code-Konfusionsmatrix (A × B)",
        "confusion_axis_a": "Report A",
        "confusion_axis_b": "Report B",
        "parse_error_no_table": "In der hochgeladenen Datei wurde keine Impuls-Tabelle gefunden. Bitte laden Sie einen TalkTrace-Report (.docx, .xlsx oder .html) hoch.",
        "parse_error_unsupported_format": "Dieses Dateiformat wird nicht unterstützt. Bitte .docx, .xlsx oder .html verwenden.",
        "unmatched_label": "unkodiert",
        "export_report": "Testergebnisse exportieren",
        "export_title": "Intercoder-Übereinstimmung exportieren",
        "export_intro": "Wähle das Ausgabeformat.",
        "no_data": "Keine Testdaten zum Exportieren vorhanden.",
        "expert_toggle": "Expertenmodus",
        "expert_toggle_hint": "Erweiterte Reliabilitätsmaße (Cohen's κ, Krippendorff's α, Fleiss' κ) mit Signifikanz-Test.",
        "expert_modal_title": "Expertenmodus — Reliabilitätsmaß wählen",
        "expert_metric_label": "Maß",
        "expert_metric_cohen": "Cohen's κ (genau 2 Coder)",
        "expert_metric_krippendorff": "Krippendorff's α (2 oder mehr Coder)",
        "expert_metric_fleiss": "Fleiss' κ (3 oder mehr Coder)",
        "expert_metric_gwet": "Gwet's AC1 (2 oder mehr Coder; robust bei seltenen Codes)",
        "expert_metric_brennan_prediger": "Brennan-Prediger κ (2 oder mehr Coder; uniforme Erwartung)",
        "expert_n_raters_label": "Anzahl Coder",
        "expert_file_label_template": "Coder {i} (.docx / .xlsx / .html)",
        "expert_compute": "Berechnen",
        "expert_cancel": "Abbrechen",
        "expert_reconfigure": "Konfiguration ändern",
        "expert_results_header": "Expertenmodus — Ergebnis",
        "expert_result_value": "Wert",
        "expert_result_ci": "95%-Konfidenzintervall",
        "expert_result_p_value": "p-Wert",
        "expert_result_n_units": "Abgeglichene Impulse",
        "expert_result_n_raters": "Anzahl Coder",
        "expert_error_too_few_files": "Bitte alle Datei-Felder befüllen, bevor du auf „Berechnen“ klickst.",
        "expert_error_invalid_n_for_metric": "Die gewählte Anzahl Coder passt nicht zum Maß.",
        "expert_error_compute_failed": "Berechnung fehlgeschlagen — bitte Eingaben prüfen.",
        "expert_computing": "Berechnung läuft …",
        "expert_metric_name_cohen": "Cohen's κ",
        "expert_metric_name_krippendorff": "Krippendorff's α",
        "expert_metric_name_fleiss": "Fleiss' κ",
        "expert_metric_name_gwet": "Gwet's AC1",
        "expert_metric_name_brennan_prediger": "Brennan-Prediger κ",
    },
    "autopilot": {
        "tab_title": "Autopilot",
        "intro_header": "Autopilot — alles in einem Klick",
        "intro_body": "Lade Transkript und Codebuch hoch, wähle zwei verschiedene LLMs und die Codierungs-Optionen — der Autopilot codiert das Transkript einmal mit jedem Modell, sichert beide Codierungen im Verlauf und übergibt sie direkt an die Testschiene zur Intercoder-Analyse.",
        "inputs_header": "1. Daten hochladen",
        "upload_transcript": "Transkript (.txt / .docx)",
        "upload_codebook": "Codebuch (.txt / .docx)",
        "status_transcript_loaded": "Transkript geladen",
        "status_transcript_missing": "Kein Transkript geladen",
        "status_codebook_loaded": "Codebuch geladen",
        "status_codebook_missing": "Kein Codebuch geladen",
        "status_source_analysis": "(aus Analyse-Tab übernommen)",
        "general_header": "2. Allgemeine Informationen",
        "options_header": "3. Codierungs-Optionen",
        "speaker_mode_label": "Welche Sprecher:innen codieren?",
        "speaker_mode_both": "Lehrperson und Schüler:innen",
        "speaker_mode_teacher": "Nur Lehrperson",
        "speaker_mode_students": "Nur Schüler:innen",
        "coders_header": "4. Zwei LLMs auswählen",
        "coder_a_label": "Coder A",
        "coder_b_label": "Coder B",
        "start_button": "Autopilot starten",
        "cancel_after_a": "Nach Coder A stoppen",
        "cancel_after_a_pending": "Stop angefragt — Coder A läuft noch durch",
        "cancelled_after_a_banner": "Autopilot vom Nutzer gestoppt — Coder B nicht ausgeführt. Coder A liegt im Results-Tab vor; eine Intercoder-Auswertung ist ohne Coder B nicht möglich.",
        "step_coder_a": "Schritt 1/2 — Codierung mit Coder A",
        "step_coder_b": "Schritt 2/2 — Codierung mit Coder B",
        "success_done": "Fertig. Wechsle zur Testschiene für die Intercoder-Auswertung.",
        "retry_b_button": "Nur Coder B wiederholen",
        "error_prefix": "Fehler",
        "error_inputs_missing": "Bitte zuerst Transkript und Codebuch hochladen.",
        "error_select_models": "Bitte für beide Coder ein Modell auswählen.",
        "error_same_model": "Coder A und Coder B müssen unterschiedliche Modelle nutzen.",
        "warning_same_model": "Coder A und B nutzen aktuell dasselbe Modell — die Übereinstimmung wäre trivial. Bitte wähle für mindestens einen Coder ein anderes Modell.",
        "results_header": "Codierungen im Vergleich",
        "results_intro": "Die vollständigen Impulstabellen beider Codierer. Für die Intercoder-Auswertung (Cohen's κ, Krippendorff's α, Konfusionsmatrix) wechsle in den Testen-Tab.",
        "results_banner_text": "Du hast den Autopilot durchlaufen lassen. Die zwei Codierungen findest du im Autopilot-Tab; die Intercoder-Auswertung im Testen-Tab. Dieser Tab zeigt nur den manuellen Einzel-Workflow.",
        "results_banner_active": "Aktive Codierung",
        "results_banner_swap": "Zu {coder} ({model}) wechseln",
        "quant_panel_title": "Quantitative Auswertung (ausklappen)",
        "quant_panel_intro": "Auf Basis des Transkripts berechnete Gesprächsanteile — gilt für beide Codierungen, da sie dasselbe Transkript nutzen.",
        "quant_box_participants": "Beteiligte Schüler:innen",
        "quant_box_participation_rate": "Beteiligungsquote",
        "quant_box_teacher_turns": "Redezüge Lehrperson",
        "quant_box_student_turns": "Redezüge Schüler:innen",
        "quant_table_title": "Statistik pro Sprecher:in",
        "quant_col_speaker": "Sprecher:in",
        "quant_col_turns": "Redezüge",
        "quant_col_words_total": "Wörter gesamt",
        "quant_col_words_avg": "Ø Wörter",
        "quant_col_words_median": "Median Wörter",
        "make_reports_switch": "Reports automatisch erzeugen",
        "make_reports_hint": "Beide Coder-Reports werden direkt nach jeder Codierung im Hintergrund gebaut — Report A ist schon herunterladbar, während Coder B noch rechnet.",
        "report_format_label": "Format",
        "report_download_a": "Report A herunterladen",
        "report_download_b": "Report B herunterladen",
        "report_pending": "Report wird erzeugt …",
        "report_failed": "Report konnte nicht erzeugt werden.",
        "report_sections_hint": "Die „im Verlauf“-Abschnitte stehen nur in der manuellen Analyse zur Verfügung.",
        "report_sec_quant_short": "Quantitativ",
        "report_sec_quali_short": "Qualitativ",
    },
    "report_options": {
        "dialog_title": "Report konfigurieren",
        "dialog_intro": "Wähle aus, welche Abschnitte enthalten sein sollen und in welchem Format.",
        "sections_label": "Inhalte",
        "sec_quant": "Quantitative Verteilung (Tabelle + Plot)",
        "sec_over_time_quant": "Beteiligung im Verlauf (Plot)",
        "sec_quali": "Qualitative Codierung (Plot + Impuls-Tabelle)",
        "sec_over_time_quali": "Code-Verteilung im Verlauf (Plot)",
        "sec_transitions": "Code-Übergänge (Heatmap + Matrix)",
        "sec_legend": "Code-Legende & Modell-Hinweis",
        "format_label": "Ausgabeformat",
        "format_docx": "DOCX (Word)",
        "format_pdf": "PDF",
        "format_xlsx": "XLSX (Excel)",
        "format_html": "HTML",
        "format_csv": "CSV (ZIP-Bündel)",
        "format_json": "JSON",
        "download_now": "Herunterladen",
        "cancel": "Abbrechen",
        "quali_disabled_hint": "Bitte zuerst die LLM-Analyse durchführen, um qualitative Optionen zu nutzen.",
        "no_section_selected": "Bitte mindestens einen Abschnitt auswählen.",
        "pdf_unavailable": "PDF-Erzeugung fehlgeschlagen (Word oder LibreOffice erforderlich).",
        "pdf_unavailable_linux": "PDF-Export wird unter Linux nicht unterstützt. Bitte stattdessen das DOCX-Format verwenden.",
        "xlsx_unavailable": "Für XLSX wird das Paket openpyxl benötigt.",
        "docx_unavailable": "Für DOCX wird das Paket python-docx benötigt.",
        "sheet_overview": "Übersicht",
        "sheet_quant": "Quant",
        "sheet_quant_over_time": "Verlauf_Quant",
        "sheet_impulses": "Impulse",
        "sheet_quali_over_time": "Verlauf_Quali",
        "sheet_transitions": "Übergänge"
    },
    "glossary": {
        "kappa": "Cohen's κ — Übereinstimmung zwischen zwei Codern, korrigiert um Zufalls-Übereinstimmung. Werte: <0 schlechter als Zufall, 0–.20 gering, .21–.40 ausreichend, .41–.60 moderat, .61–.80 substanziell, .81–1.0 fast perfekt. Cohen (1960).",
        "krippendorff_alpha": "Krippendorff's α — Reliabilitätsmaß für 2+ Coder, robust gegenüber unbalancierten Verteilungen und fehlenden Werten. Konvention: ≥.80 gut, .67–.79 vorläufig brauchbar. Krippendorff (2004).",
        "fleiss_kappa": "Fleiss' κ — Verallgemeinerung von Cohen's κ auf 3+ Coder bei konstanter Coder-Zahl pro Einheit. Fleiss (1971).",
        "gwet_ac1": "Gwet's AC1 — Übereinstimmungs-Index, robust gegenüber dem Kappa-Paradox bei sehr ungleicher Code-Verteilung. Gwet (2008).",
        "brennan_prediger": "Brennan-Prediger κ — Übereinstimmung mit gleichverteilten Erwartungswerten; weniger empfindlich für seltene Codes als Cohen's κ. Brennan & Prediger (1981).",
        "percent_agreement": "Prozentuale Übereinstimmung — Anteil der Einheiten, in denen beide Coder denselben Code vergeben. Intuitiver Basiswert; ignoriert aber Zufalls-Übereinstimmung.",
        "f1": "F1-Score — harmonisches Mittel aus Präzision und Trefferquote für einen einzelnen Code. 1.0 = perfekt, 0 = nichts richtig zugeordnet.",
        "precision": "Präzision (Precision) — Anteil korrekter Zuordnungen unter allen vom Coder B vergebenen Vorkommen dieses Codes. „Wenn Coder B den Code vergibt, wie oft hat Coder A ihn ebenfalls?“",
        "recall": "Trefferquote (Recall) — Anteil korrekter Zuordnungen unter allen tatsächlichen (Coder A) Vorkommen dieses Codes. „Wenn Coder A den Code vergibt, wie oft trifft Coder B ihn ebenfalls?“",
        "confusion_matrix": "Konfusionsmatrix — Tabelle, die Code-Verwechslungen zwischen zwei Codern auflistet. Diagonale = Übereinstimmung; Off-Diagonale = Verwechslungen.",
        "ci": "95%-Konfidenzintervall (Bootstrap, n=1000 Resamples) — Bereich, in dem der wahre Wert mit 95% Wahrscheinlichkeit liegt.",
        "p_value": "p-Wert — Wahrscheinlichkeit, das beobachtete (oder ein extremeres) Ergebnis unter H₀ (κ=0) zu sehen. ***<.001, **<.01, *<.05, n.s. sonst.",
        "n_pairs": "Abgeglichene Paare — Gesamtzahl der Impulse, die mindestens in einem Report codiert wurden.",
        "n_both": "Von beiden codiert — Anzahl Impulse, die in beiden Reports auftauchen.",
        "n_only": "Nur in einem — Impulse, die nur einer der Reports erfasst hat (fließen als „unkodiert“ ein)."
    },
    "onboarding": {
        "demo_button": "Mit Beispieldaten ausprobieren",
        "demo_loaded": "Beispiel geladen — schau dir den Ergebnisse-Tab an.",
        "welcome_title": "Willkommen bei TalkTrace AI",
        "welcome_intro": "In drei Schritten loslegen:",
        "welcome_step_1": "API-Key unter Optionen eintragen (oder Ollama lokal nutzen).",
        "welcome_step_2": "Transkript und Codebuch im Analyse-Tab hochladen.",
        "welcome_step_3": "„Analysieren\" klicken — quantitative Ergebnisse erscheinen sofort, qualitative Codierung sobald das LLM antwortet.",
        "welcome_demo_hint": "Oder klicke auf „Mit Beispieldaten ausprobieren\" und überspringe das Setup.",
        "welcome_close": "Verstanden",
        "welcome_dont_show": "Nicht mehr zeigen",
        "empty_results_message": "Lade im Analyse-Tab ein Transkript und ein Codebuch hoch und klicke auf „Analysieren\".",
        "quickstart_title": "Quick-Start",
        "quickstart_api_key": "API-Key vorhanden",
        "quickstart_model": "Modell ausgewählt",
        "quickstart_transcript": "Transkript hochgeladen",
        "quickstart_codebook": "Codebuch hochgeladen",
        "quickstart_analysis_done": "Analyse durchgeführt",
        "quickstart_status_ok": "Alles bereit",
        "quickstart_status_pending": "Schritte offen",
        "tooltip_group_id": "Freier Bezeichner für diese Diskussion. Wird als Report-Überschrift und Dateinamen-Suffix verwendet.",
        "tooltip_num_pupils": "Gesamtgröße der Gruppe (z.B. alle Schüler:innen der Klasse). Wird als Referenz für die Beteiligungsquote (aktive Sprecher:innen / Gesamtgröße) verwendet — bitte manuell eintragen.",
        "tooltip_name_teacher": "Wie die Lehrperson im Transkript bezeichnet wird (z.B. TEACHER, LEHRER, Frau Müller). Muss exakt zum Transkript passen.",
        "tooltip_upload_transcript": "Plain Text oder .docx. Format: ein Beitrag pro Zeile, z.B. „S01: …\". Bei SPEAKER_00-Format „Transkript konvertieren\" nutzen.",
        "tooltip_upload_codebook": "Liste der Codes, die das LLM verwenden darf. Plain Text oder .docx. Jeder Code mit Shortcode + kurzer Beschreibung.",
        "tooltip_llm_switch": "Schaltet die qualitative Codierung per LLM ein/aus. Aus = nur quantitative Statistik (kein API-Aufruf, kostenlos).",
        "tooltip_model_select": "Modell für die qualitative Codierung. Größere Modelle kosten mehr, liefern aber bessere Codes.",
        "dp_title": "Datenschutz-Hinweis",
        "dp_intro_strong": "Bitte vor der ersten Nutzung lesen.",
        "dp_intro_body": "TalkTrace sendet Transkripte und Codebücher an den ausgewählten LLM-Anbieter. Bei OpenAI, Anthropic und Groq verlassen die Daten den europäischen Wirtschaftsraum (Server in den USA). Bestätige bitte, mit welcher Datengrundlage du arbeitest:",
        "dp_choice_label": "Womit arbeitest du?",
        "dp_choice_consent": "Ich verwende ausschließlich Transkripte, für die eine schriftliche Einwilligung zur KI-gestützten Verarbeitung (auch in den USA) der betroffenen Personen vorliegt.",
        "dp_choice_fictive": "Ich verwende ausschließlich fiktive Testdaten (z.B. selbst ausgedacht oder KI-generiert) ohne Bezug zu realen Personen.",
        "dp_consent_hint": "Hinweis: Wenn du nur lokale Modelle nutzen möchtest, schalte in den Optionen unter „Erweitert\" den Modus „Nur lokal (Ollama)\" an. Cloud-Modelle (auch „Ollama Cloud\") werden dann automatisch ausgeblendet.",
        "dp_confirm": "Ich bestätige",
        "dp_pick_required": "Bitte eine der beiden Optionen auswählen, bevor du fortfährst."
    },
    "start": {
        "tab_title": "Start",
        "intro_headline": "Willkommen bei TalkTrace AI",
        "intro_body": "TalkTrace analysiert Unterrichts- und Gruppengespräche: quantitative Kennzahlen, qualitative Codierung per LLM und exportierbare Berichte. Wähle unten einen Einstieg oder folge dem Arbeitsablauf von links nach rechts.",
        "workflow_title": "So läuft es ab",
        "workflow_audio": "Audio",
        "workflow_transcript": "Transkript",
        "workflow_analysis": "Analyse",
        "workflow_feedback": "Feedback",
        "workflow_export": "Export",
        "status_done": "erledigt",
        "status_pending": "offen",
        "tiles_title": "Schnelleinstieg",
        "tile_tseda_title": "T-SEDA-Analyse",
        "tile_tseda_body": "Unterrichtsgespräch mit dem integrierten T-SEDA-Codebuch analysieren — nur noch Transkript hochladen.",
        "tile_audio_title": "Mit Audio beginnen",
        "tile_audio_body": "Aufnahme lokal transkribieren — der Ton verlässt deinen Rechner nicht.",
        "tile_transcript_title": "Mit Transkript beginnen",
        "tile_transcript_body": "Transkript und Codebuch hochladen und die Analyse starten.",
        "tile_resume_title": "Letzte Sitzung laden",
        "tile_resume_body": "An einer gespeicherten Analyse aus dem Verlauf anknüpfen.",
        "tile_demo_title": "Demo ansehen",
        "tile_demo_body": "Ein fertiges Beispiel laden — ganz ohne API-Key.",
        "config_title": "Aktuelle Konfiguration",
        "config_line_template": "Anbieter: {provider} · Modell: {model} · {status}",
        "config_line_ready": "bereit",
        "config_line_no_key": "kein API-Key hinterlegt",
        "config_line_no_provider": "Noch kein LLM konfiguriert — im Analyse-Tab einrichten.",
        "quickstart_title": "Quick-Start",
        "whats_new_title": "Was ist neu?",
        "whats_new_1": "T-SEDA-Vorlage: integriertes Codebuch per Klick — nur noch Transkript hochladen.",
        "whats_new_2": "Mehrfach-Codierung mit Konfidenz: bis zu 2 Codes pro Beitrag in eigenen Spalten + zweite Prüfrunde für uncodierte Beiträge.",
        "whats_new_3": "Eigene OpenAI-kompatible Endpoints + Modell-Refresh für alle Anbieter.",
        "dp_section_title": "Datenschutz",
        "dp_intro_strong": "Bitte vor der ersten Analyse bestätigen.",
        "dp_intro_body": "TalkTrace sendet Transkripte und Codebücher an den ausgewählten LLM-Anbieter. Bei OpenAI, Anthropic und Groq verlassen die Daten den europäischen Wirtschaftsraum (Server in den USA). Bestätige bitte, mit welcher Datengrundlage du arbeitest:",
        "dp_choice_consent": "Ich verwende ausschließlich Transkripte, für die eine schriftliche Einwilligung zur KI-gestützten Verarbeitung (auch in den USA) der betroffenen Personen vorliegt.",
        "dp_choice_fictive": "Ich verwende ausschließlich fiktive Testdaten (z.B. selbst ausgedacht oder KI-generiert) ohne Bezug zu realen Personen.",
        "dp_choice_self": "Ich analysiere ausschließlich meine eigenen Sprechakte (z.B. als Lehrkraft die eigenen Äußerungen); fremde Personen werden nicht ausgewertet.",
        "dp_confirm": "Ich bestätige",
        "dp_pick_required": "Bitte eine der Optionen auswählen, bevor du fortfährst.",
        "dp_status_pending": "Datenschutz noch nicht bestätigt — vor der ersten Analyse erforderlich.",
        "dp_status_ok": "Datenschutz bestätigt:",
        "dp_kind_consent": "Einwilligung liegt vor",
        "dp_kind_fictive": "fiktive Testdaten",
        "dp_kind_self": "nur eigene Sprechakte",
        "dp_change": "Ändern"
    }
}
