STRINGS = {
    "sidebar": {
        "title": "Sidebar",
        "provider_select": "Provider",
        "model_select": "Choose a LLM",
        "llm_switch": "LLM Analysis",
        "analyse_teacher_switch": "Analyze teacher",
        "analyse_students_switch": "Analyze students",
        "multi_coding_switch": "Allow multi-coding",
        "prompt_filter_teacher_only": "\n\nIMPORTANT: Code ONLY utterances made by the teacher ({teacher_name}). Ignore all utterances made by students.",
        "prompt_filter_students_only": "\n\nIMPORTANT: Code ONLY utterances made by students. Ignore all utterances made by the teacher ({teacher_name}).",
        "prompt_filter_none": "\n\nIMPORTANT: No speaker group is selected. Please enable at least one of \"Analyze teacher\" or \"Analyze students\" in the sidebar.",
        "user_prompt_filter_teacher_only": "\n\nPlease code ONLY utterances by the teacher ({teacher_name}) in this transcript. Skip every student utterance (S01, S02, ...) entirely.",
        "user_prompt_filter_students_only": "\n\nPlease code ONLY student utterances (S01, S02, ...) in this transcript. Skip every utterance by the teacher ({teacher_name}) entirely.",
        "user_prompt_filter_none": "\n\nNo speaker group is currently enabled — no coding should be produced.",
        "prompt_multi_coding_on": "\n\nIMPORTANT: If multiple codes from the codebook apply to a single utterance, assign the best-fitting ones — emit one separate entry per matching code, with identical 'Sprecher' and 'Impuls' but different 'Shortcode'. Assign AT MOST TWO codes per utterance, most certain first. Add to EVERY entry, as its last field, 'Konfidenz': an integer from 0 to 100 expressing how certain you are that the code applies. CALIBRATE the confidence across the full scale, grounding it in textual evidence: 90+ ONLY for an unambiguous fit that is literally supported by the wording; 60–75 = plausible but debatable; below 50 = speculative. Do not assign the same default value to many utterances — different utterances carry different amounts of evidence. Very short utterances without content of their own justify at most medium confidence. Name the best candidates even when you are uncertain — the confidence value makes the uncertainty transparent. When an utterance covers multiple distinct aspects or themes (more common in longer utterances), assign one separate code per aspect — length is only an indicator; what matters is thematic diversity. If clearly NO code applies to an utterance, simply omit it — it will appear with an empty Shortcode in the report. Code the ENTIRE transcript to the end; do not stop early.",
        "prompt_multi_coding_off": "\n\nIMPORTANT: Assign AT MOST ONE code from the codebook to each utterance — the most fitting one. If NO code from the codebook applies, omit the utterance from the output (it will appear with an empty Shortcode in the report). Do not multi-code; each utterance appears at most once in the output.",
        "user_prompt_multi_coding_on": "\n\nNote: If multiple codes fit a single utterance, emit each assignment as its own entry (same 'Sprecher' and 'Impuls', different 'Shortcode') — at most two codes per utterance, most certain first. Every entry gets 'Konfidenz' as its last field (integer 0-100, how certain the code applies); calibrate across the full scale (90+ only for unambiguous textual evidence, 60–75 plausible but debatable, below 50 speculative — no blanket default value; very short utterances without content of their own at most medium) and name candidates even when uncertain, the confidence makes that transparent. Pay particular attention to longer utterances: check whether they cover multiple distinct aspects or themes — if so, assign one code per aspect. If clearly no code fits, omit the utterance. Code the transcript completely up to the last utterance — do not terminate the list early.",
        "user_prompt_multi_coding_off": "\n\nNote: Assign AT MOST ONE code per utterance — the most fitting one. If no code applies, omit the utterance. Each utterance appears at most once in the output.",
        "prompt_context": "\n\nIMPORTANT: Code every turn IN THE CONTEXT of the conversation, not in isolation. Whether an utterance builds on an idea, challenges it, gives a reason or answers a question often only becomes clear from its relation to the preceding turns — so take the surrounding turns into account for every coding decision (e.g.: a brief student answer after a why-question is a justification; a 'No, but …' after a proposal is a challenge). The code is still assigned per turn.",
        "user_prompt_context": "\n\nNote: Every turn is coded in the light of the conversational flow — read the surrounding turns before each coding decision, because the function of an utterance (building, challenging, reasoning, answering) often only shows in relation to what came before. The code is still assigned per turn.",
        "prompt_relevance": "\n\nIMPORTANT: Not every turn is a codable move — regardless of which code might seem to apply, the following stay UNCODED: (a) merely nominating or calling on a person, i.e. turns consisting only of a name or speaker label, even with a hand-over filler ('S2?', 'Okay. S10?'); (b) turns consisting EXCLUSIVELY of an acknowledgement or minimal response ('Yes.', 'Exactly.', 'Okay.', 'Mhm.', 'I see.'); (c) unintelligible passages and transcription placeholders such as '(inaudible)' or '(unv.)'. For such turns emit NO entry at all — not even one with low confidence. This rule takes precedence over the instruction to name uncertain candidates: a non-move is not coded at 0-20 %, it is omitted. CAUTION, common mistake: the rule applies ONLY when the ENTIRE turn consists of the acknowledgement. If a turn starts with 'Yes', 'Exactly' or 'Okay' and then continues with content, code it COMPLETELY NORMALLY — e.g. 'Yes, that's not quite right about the one-euro jobs, because they …' is a full contribution (here: challenge), likewise 'Exactly. So that was the origin …'. EXCEPTION for genuinely short turns too: the conversational context clearly makes them a substantive move — e.g. a firm 'No.' disagreeing with a proposal, or a brief factual answer to a question.",
        "user_prompt_relevance": "\n\nNote: Mere nomination (turn = only a name/label, possibly with a filler), turns consisting EXCLUSIVELY of an acknowledgement ('Yes.', 'Exactly.', 'Okay.', 'Mhm.') and unintelligible bits ('(inaudible)', '(unv.)') stay uncoded — emit no entry for them at all, not even a low-confidence one (this takes precedence over the rule about naming uncertain candidates). IMPORTANT: if a turn merely starts with 'Yes/Exactly/Okay' and then continues with content, code it completely normally — the rule only covers turns that consist of nothing but the acknowledgement. Exception: the context makes a genuinely short turn a substantive move (disagreement, brief factual answer).",
        "second_pass_prompt": "\n\nSECOND REVIEW PASS: The turns listed below were left WITHOUT a code in a first coding pass. You have the full transcript as context — but code ONLY the listed turns, re-checking each one carefully against the codebook in the light of the conversational flow. It is perfectly legitimate for turns to stay uncoded (e.g. merely nominating a person, pure organisation) — assign a code ONLY if it is clearly supported by the text and its context. Emit fitting codes in the usual format; keep omitting turns without a fitting code.\n\nTurns to re-check:\n{pending_list}",
        "second_pass_running": "Second review pass: re-checking {n} uncoded turn(s) …",
        "second_pass_done": "Second review pass finished: {n_new} additional coding(s) across {n_checked} re-checked turns.",
        "button_analysis": "Analyze",
        "button_cancel_analysis": "Cancel",
        "cancel_disabled_streaming_off": "Cancellation requires streaming to be enabled (see Options).",
        "analysis_completed": "Analysis Completed!",
        "download_report": "Download Report",
        "import_session": "Import Session",
        "export_session": "Export Session",
        "reset_session": "Reset Session",
        "history_button": "History",
        "history_title": "Analysis history",
        "history_save_now": "Save current session to history",
        "history_load": "Load",
        "history_delete": "Delete",
        "history_empty": "No saved sessions yet.",
        "history_select_label": "Select a saved session",
        "history_col_date": "Date",
        "history_col_model": "Model",
        "history_col_group": "Group",
        "history_col_turns": "Turns",
        "history_saved_ok": "Saved to history.",
        "history_loaded_ok": "Session loaded.",
        "history_deleted_ok": "Entry deleted.",
        "history_save_blocked": "Run an analysis first before saving to history.",
        "history_close": "Close",
        "cost_prediction": "Minimal Cost Estimation",
        "tokens_aprox": "Input-Tokens: approx.",
        "ollama_cloud_hint": "Note: Ollama Cloud is free and good for testing with shorter transcripts and codebooks. Response times vary a lot with server load. For longer transcripts or production runs, consider a paid provider (OpenAI/Anthropic/Groq) or local Ollama (\"ollama serve\").",
        "ollama_cloud_hint_label": "Cloud notice",
        "groq_quality_hint": "Note: Groq is very fast and good for testing. Output quality can be inaccurate or unreliable, though. For serious analyses prefer OpenAI or Anthropic.",
        "groq_quality_hint_label": "Quality notice",
        "openrouter_hint": "OpenRouter is a gateway service that routes requests to third-party providers (DeepSeek, Qwen, Mistral, etc.). Best suited for cheap/short test runs and cross-model validation; long transcripts paired with reasoning models can hit per-model max_tokens variability and gateway-typical latency that dampens the UX — for production-grade long analyses, prefer the underlying provider's direct API (OpenAI, Anthropic, …). Data goes through OpenRouter and on to the underlying provider — review data-protection terms before using in school contexts. Model names use the 'provider/model' format (e.g. 'deepseek/deepseek-v4-pro').",
        "openrouter_hint_label": "OpenRouter notice",
        "localmind_hint": "LocalMind is an EU-hosted (Austria), OpenAI-compatible inference gateway and the privacy-friendly default: transcripts never leave the EU. A single key gives access to many models (its own 'localmind-*' models plus Llama, Mistral, Qwen, Gemma, DeepSeek and more). The exact model slugs are a live catalogue — pull them via 'Load LocalMind models' in the Options tab. Reasoning models spend output budget on internal chain-of-thought; for very long transcripts prefer an instruct model.",
        "localmind_hint_label": "LocalMind notice",
        "custom_hint": "Custom OpenAI-compatible endpoint — base URL and API key are configured in the Options tab. Suited for self-hosted servers (vLLM, llama.cpp) or institutional gateways. Where the data ends up depends on the configured endpoint — review data protection yourself before using real transcripts.",
        "custom_hint_label": "Endpoint notice",
        "mistral_hint": "Mistral is a French frontier-model lab; the chat-completion API is hosted in the EU (Paris / Frankfurt regions), which makes it the natural GDPR-conformant cloud-LLM choice for school deployments that cannot route data to the US. Strong long-context behaviour at moderate cost. The 'magistral-*' models are reasoning models — they spend output budget on internal chain-of-thought; for very long transcripts prefer 'mistral-large-latest' or 'mistral-medium-latest'.",
        "mistral_hint_label": "Mistral notice",
        "deepseek_hint": "DeepSeek delivers frontier-class quality at a fraction of OpenAI/Anthropic cost (deepseek-chat ~ $0.27/$1.10 per 1M tokens; deepseek-reasoner ~ $0.55/$2.19) — the cost compression makes multi-coder reliability studies feasible that would otherwise blow the budget. 'deepseek-reasoner' is an R1-class reasoning model; its chain-of-thought is hidden from the output but consumes the token budget, so for long transcripts prefer 'deepseek-chat'. API is hosted by DeepSeek (CN) — review data-protection terms for school use.",
        "deepseek_hint_label": "DeepSeek notice",
    },
    "analysis": {
        "tab_title": "Analysis",
        "llm_config_title": "LLM configuration",
        "general_info": "General Information",
        "group_id": "Group ID",
        "num_pupils": "Group size",
        "name_teacher": "Teacher Name in Transcript",
        "name_teacher_var": "TEACHER",
        "document_input": "Document Input",
        "upload_transcript": "Upload Transcript",
        "upload_codebook": "Upload Codebook",
        "template_label": "Or use a template:",
        "template_tseda_button": "Load T-SEDA codebook",
        "template_tseda_hint": "Built-in codebook for dialogic classroom talk (T-SEDA Collective 2023, University of Cambridge, CC BY) — automatically sets: code teacher AND students (context-aware), multi-coding with confidence.",
        "template_tseda_loaded": "T-SEDA codebook loaded. Presets active: code teacher and students (in conversational context), up to 2 codes per turn with confidence. Now just upload the transcript.",
        "preview_codebook": "Codebook Preview",
        "preview_transcript": "Transcript Preview",
        "placeholder": "No file selected",
        "browse": "Browse...",
        "placeholder_codebook": "No codebook uploaded...",
        "placeholder_transcript": "No transcript uploaded...",
        "modal_restart_analysis": "Please upload codebook and restart the analysis (without LLM)!",
        "modal_title_attention": "Attention",
        "modal_reset_session": "Are you sure you want to reset the session? All unsaved data will be lost.",
        "modal_title_reset": "Reset Session",
        "modal_title_error": "Error",
        "modal_confirm_reset": "Yes, reset!",
        "modal_button_cancel": "Cancel",
        "modal_button_close": "Close",
        "cancelled_banner_title": "Analysis cancelled",
        "cancelled_banner_body": "{n} impulse(s) were coded before the cancellation. These partial results are incomplete and not suitable as a final coding — please let the analysis run to completion for definitive evaluations.",
        "modal_upload_transcript_first": "Please upload a transcript first!",
        "modal_upload_codebook_first": "Please upload a codebook first!",
        "teacher_not_found": "Teacher name not found in transcript.",
        "check_format_tooltip": "Checks the uploaded transcript for the expected format (S01, S02, ...). If the format differs (e.g., SPEAKER_00 with line breaks within turns), a converted version is generated and offered for download. The file type (txt, docx) is preserved.",
        "format_status_valid": "Format is valid — no conversion needed.",
        "format_status_invalid": "Format differs — open the wizard to convert.",
        "format_status_unsupported": "File type not supported — please use .txt or .docx (without tables).",
        "modal_title_format_check": "Transcript Format Check",
        "modal_format_already_valid": "The transcript is already in the correct format.",
        "modal_format_invalid_confirm": "The transcript is not in the expected format. A converted version has been generated. Preview of the first lines:",
        "modal_format_pdf_unsupported": "Format conversion is not supported for PDF files. Please upload a .txt or .docx file.",
        "modal_format_docx_table": "This .docx file contains a table and cannot be converted as a transcript.",
        "download_converted": "Download converted transcript",
        "format_modal_speakers_title": "Map speakers",
        "format_modal_speakers_intro": "The following speakers were detected in the transcript. Choose how each one should be labeled in the converted file.",
        "format_modal_speakers_col_raw": "Detected speaker",
        "format_modal_speakers_col_target": "Mapping",
        "format_speaker_role_teacher": "Teacher",
        "format_speaker_role_student_n": "Student {n}",
        "format_speaker_role_ignore": "Ignore",
        "format_modal_brackets_title": "Action descriptions",
        "format_modal_brackets_intro": "The following bracket-style annotations were detected. Decide whether to keep or remove them.",
        "format_bracket_keep": "Keep",
        "format_bracket_strip": "Remove",
        "format_modal_preview_title": "Preview",
        "format_modal_button_next": "Next",
        "format_modal_button_back": "Back",
        "format_modal_button_convert": "Convert",
        "format_modal_no_speakers": "No speakers could be detected automatically. The transcript cannot be converted.",
        "format_bracket_samples": "Examples"
    },
    "noscribe": {
        "tab_title": "Transcription",
        "section_title": "Audio transcription (local)",
        "checking": "Checking engine …",
        "not_installed_intro": "Create transcripts straight from audio recordings — entirely on this machine, with the recording never leaving your computer. Powered by the open-source noScribe engine (Whisper + pyannote).",
        "bullet_local": "100% local: audio is never sent to any server.",
        "bullet_size": "A one-time install downloads about 3 GB (engine + Whisper model).",
        "bullet_gpl": "Uses the external open-source project noScribe (GPL-3.0), fetched from GitHub during install.",
        "windows_only": "Automatic engine installation is only available on Windows in this version.",
        "broken_note": "A previous installation did not complete. It is safe to run the install again — already-downloaded parts are reused.",
        "install_button": "Install transcription engine",
        "repair_button": "Repair installation",
        "installing_title": "Installing engine …",
        "ready_intro": "Pick an audio file, set the options, then transcribe. The finished transcript is loaded into the Analysis tab (transcript field) automatically.",
        "audio_label": "Audio file",
        "output_label": "Save transcript as",
        "output_placeholder": "File name (without extension)",
        "language_label": "Language",
        "language_auto": "Automatic",
        "language_de": "German",
        "language_en": "English",
        "model_label": "Model",
        "model_needs_download": "{name} (downloads ~{gb} GB)",
        "speakers_label": "Speakers",
        "speakers_auto": "Automatic",
        "speakers_none": "None",
        "speakers_hint_auto": "Tip: Setting a fixed number of speakers markedly "
                              "improves automatic speaker separation. Only choose "
                              "\"Automatic\" if the count is genuinely unknown.",
        "speakers_hint_fixed": "Fixed speaker count set – this improves speaker "
                               "separation.",
        "pause_label": "Mark pauses",
        "pause_none": "None",
        "start_time_label": "Start (hh:mm:ss)",
        "stop_time_label": "Stop (hh:mm:ss)",
        "trim_label": "Trim (waveform)",
        "trim_hint": "Use the handles to set start and end — only the selected range is "
                     "transcribed; the Start/Stop fields are filled in automatically.",
        "trim_play": "Play selection",
        "trim_pause": "Pause",
        "trim_reset": "Reset",
        "trim_region": "Range",
        "trim_decoding": "Loading waveform …",
        "trim_failed": "Waveform not available for this format — enter Start/Stop manually if needed.",
        "download_txt": "Save transcript (.txt)",
        "overlapping_label": "Overlapping speech",
        "disfluencies_label": "Disfluencies (uh, um …)",
        "timestamps_label": "Timestamps",
        "start_button": "Transcribe",
        "running_title": "Transcribing …",
        "cancel_button": "Cancel",
        "step_of": "Step {n} of {total}",
        "progress_log_summary": "Details",
        "editor_title": "Edit transcript",
        "editor_hint": "One row = one turn. Double-click a cell to fix the speaker (e.g. S01) or the text. „Apply“ saves the changes for the analysis and writes them to the transcript file.",
        "editor_placeholder": "The transcript appears here after transcription. You can also paste or edit it manually.",
        "editor_col_speaker": "Speaker",
        "editor_col_text": "Utterance",
        "editor_apply": "Apply",
        "editor_apply_hint": "Saves the changes for the analysis and to the transcript file.",
        "editor_applied": "Transcript applied for the analysis.",
        "editor_applied_saved": "Applied — analysis updated and saved to „{file}“.",
        "editor_edit_marker": "(transcript manually edited: {date})",
        "done_msg": "Transcript ready — in the field below and on the Analysis tab.",
        "desktop_detected": "An existing noScribe desktop installation was detected and will be used.",
        "engine_version": "Engine: noScribe {version}",
        "uninstall_button": "Uninstall engine",
        "uninstall_title": "Uninstall engine",
        "uninstall_confirm": "The transcription engine and the downloaded model (about 3 GB) will be removed completely. Continue?",
        "no_audio_selected": "Please select an audio file first.",
        "error_title": "Transcription failed",
        "error_log_summary": "Show technical details",
        "error_retry": "Try again",
        "phase_preflight": "Checking requirements",
        "phase_uv": "Preparing installer",
        "phase_python": "Creating Python environment",
        "phase_noscribe": "Downloading noScribe",
        "phase_deps": "Installing dependencies (~2 GB)",
        "phase_model": "Downloading Whisper model (~0.8 GB)",
        "phase_health": "Verifying installation",
        "phase_setup": "Preparing audio",
        "phase_diarize": "Identifying speakers",
        "phase_whisper_load": "Loading speech recognition",
        "phase_transcribe": "Transcribing",
        "phase_save": "Saving transcript",
    },
    "consent": {
        # --- tab / form UI ---
        "tab_title": "Consent",
        "section_title": "Generate consent declaration",
        "intro_hint": "Generate a print-ready consent declaration (GDPR Art. 13) for teachers "
                      "who have their own speaking behaviour analysed. Adjust the fields, generate "
                      "a preview, download it as HTML and print it.",
        "disclaimer": "This template is an aid, not legal advice. Please have it reviewed by your "
                      "data protection officer before use and adapt it to your state/institution "
                      "where necessary.",
        "field_project_name": "Name of the training/project",
        "field_responsible": "Responsible party (name, institution, contact)",
        "field_dpo": "Data protection officer (optional)",
        "field_purpose": "Purpose of processing",
        "field_legal_basis": "Legal basis",
        "field_data_categories": "Data categories",
        "field_llm_mode": "Analysis by AI service",
        "field_llm_mode_cloud": "Cloud provider (e.g. OpenAI)",
        "field_llm_mode_local": "Local / EU (no third-country transfer)",
        "field_llm_provider": "AI service (name, country)",
        "field_storage": "Storage duration",
        "field_revocation": "Contact for withdrawal",
        "field_authority": "Supervisory authority (optional)",
        "field_participant_name": "Teacher's name (optional, for the output)",
        "field_place_date": "Place, date (optional)",
        "per_participant_heading": "Per teacher (optional)",
        "generate_button": "Generate preview",
        "download_docx": "As Word (.docx)",
        "download_pdf": "As PDF",
        "pdf_failed": "PDF generation failed (Word required): {error}",
        "preview_empty": "No preview yet. Fill in the fields and click “Generate preview”.",
        # --- prefilled defaults (generic, editable) ---
        "default_project_name": "Teacher training – analysis of one's own speaking behaviour",
        "default_purpose": "Analysis of your own speaking and conversational behaviour for training "
                           "and reflection purposes.",
        "default_legal_basis": "Consent (Art. 6(1)(a) GDPR)",
        "default_data_categories": "An audio recording of your own voice and the transcript "
                                   "automatically generated from it.",
        "default_storage": "until the end of the training",
        # --- placeholders (institution-specific, must be filled) ---
        "ph_responsible": "e.g. TU Dortmund, Institute …, Prof. …, address, e-mail",
        "ph_dpo": "Name and contact of the data protection officer",
        "ph_revocation": "e.g. functional e-mail of the training team",
        "ph_authority": "e.g. State Data Protection Commissioner, contact",
        "ph_participant_name": "First and last name",
        "ph_place_date": "e.g. Dortmund, 2026-06-10",
        "ph_llm_provider": "e.g. OpenAI, USA",
        # --- 'field missing' inline warnings on the document ---
        "missing_responsible": "Responsible party missing",
        "missing_purpose": "Purpose missing",
        "missing_legal_basis": "Legal basis missing",
        "missing_data_categories": "Data categories missing",
        "missing_storage": "Storage duration missing",
        "missing_revocation": "Withdrawal contact missing",
        # --- generated document ---
        "doc_lang": "en",
        "doc_title": "Consent Declaration",
        "doc_project_generic": "this training",
        "doc_provider_generic": "the configured AI service",
        "doc_purpose_generic": "the purpose stated above",
        "doc_part1_heading": "Study information",
        "doc_part2_heading": "Data protection information (Art. 13 GDPR)",
        "doc_part3_heading": "Consent declaration",
        "doc_intro": "As part of {project} we analyse your own use of language in order to give you "
                     "feedback on your speaking and conversational behaviour. For this purpose an "
                     "audio recording of your own utterances is made.",
        "doc_pipeline": "The recording is first transcribed directly on the device (speech "
                        "recognition); the audio file does not leave the device in the process. "
                        "The transcript (text) is then evaluated for the analysis.",
        "doc_art13_intro": "We process your data in accordance with the provisions of the General "
                           "Data Protection Regulation (GDPR). With the following notes we fulfil "
                           "our duty to inform under Article 13 GDPR.",
        "doc_responsible_label": "Responsible party",
        "doc_dpo_label": "Data protection officer",
        "doc_purpose_label": "Purpose of processing",
        "doc_legal_basis_label": "Legal basis",
        "doc_data_categories_label": "Data categories",
        "doc_recipients_label": "Recipients of the data",
        "doc_transcription_note": "Transcription: speech recognition runs locally on the device "
                                  "used. The audio recording is not transmitted to third parties.",
        "doc_recipients_cloud": "Analysis: for the evaluation, the transcript text is transmitted "
                                "to the following service: {provider}. If this provider processes "
                                "outside the EU/EEA, this constitutes a transfer to a third country; "
                                "a level of data protection equivalent to that of the EU cannot "
                                "always be guaranteed there.",
        "doc_recipients_local": "Analysis: the transcript is evaluated locally or on a service "
                                "within the EU/EEA. No transfer to a third country takes place.",
        "doc_storage_label": "Storage",
        "doc_storage_sentence": "We store your personal data {duration}. The data are then deleted "
                                "or anonymised.",
        "doc_rights_label": "Your data subject rights",
        "right_withdraw": "Right to withdraw: you have the right to withdraw your consent at any "
                          "time with effect for the future.",
        "right_access": "Right of access: you have the right to know which personal data of yours "
                        "are being processed.",
        "right_rectify": "Right to rectification: you have the right to have incorrect personal "
                         "data corrected.",
        "right_erase": "Right to erasure: you can request the deletion of your data at any time.",
        "right_restrict": "Right to restriction of processing: you can request the restriction of "
                          "processing.",
        "right_portability": "Right to data portability: you have the right to receive the personal "
                             "data concerning you in a structured, commonly used and machine-readable "
                             "format.",
        "right_object": "Right to object: you can object to the processing of the data concerning "
                        "you at any time.",
        "right_complaint": "Right to lodge a complaint with a supervisory authority: if you believe "
                           "that data protection regulations have not been observed in the processing "
                           "of your data, you can contact the competent supervisory authority.",
        "doc_rights_contact": "To exercise your rights, please contact: {responsible}",
        "doc_revocation_sentence": "Please send your withdrawal to: {revocation}",
        "doc_authority_label": "Supervisory authority",
        "doc_voluntary": "I am aware that my participation is voluntary and that I will not suffer "
                         "any disadvantage if I refuse my consent. I can withdraw my consent at any "
                         "time with effect for the future. No reasons need be given for withdrawing "
                         "consent and no disadvantages arise from it. In the event of withdrawal, my "
                         "personal data will be deleted immediately. Withdrawal of consent does not "
                         "affect the lawfulness of the processing carried out on the basis of the "
                         "consent up to the withdrawal.",
        "doc_consent_main": "I consent to my audio recording and the transcript generated from it "
                            "being processed for the following purpose: {purpose}",
        "doc_consent_cloud": "I consent to the transcript text being transmitted to {provider} for "
                             "analysis (possibly a third-country transfer, see above).",
        "doc_consent_participate": "I hereby consent to take part in {project}.",
        "doc_yes": "Yes",
        "doc_no": "No",
        "doc_name_line": "First and last name in block letters",
        "doc_signature_line": "Place, date, signature",
        "doc_footer": "Template based on the CC0-licensed Consent-Gen-RDMO (TU Dortmund). This "
                      "declaration is an aid and not legal advice — please have it reviewed by your "
                      "data protection officer before use.",
    },
    "results": {
        "tab_title": "Results",
        "no_results": "Please perform the analysis first!",
        "no_results_title": "No results yet",
        "autopilot_chooser_title": "Which coding to display?",
        "autopilot_chooser_intro": "The Autopilot produced two codings. Which one do you want to display in the Results tab?",
        "no_data": "No data available yet",
        "section_quantitative_analysis": "Quantitative Distribution of Conversation Shares",
        "class_size": "Class Size",
        "num_participants": "Number of Participating Students",
        "participation_rate": "Participation Rate",
        "distribution_of_turns": "Distribution of Conversation Turns",
        "interaction_turns": "Conversation Turns",
        "teacher": "Teacher",
        "students": "Students",
        "turn_count": "Number of Turns",
        "turn_length": "Length in Words M (SD)",
        "teacher_turns_box": "Teacher turns",
        "pupils_turns_box": "Student turns",
        "longest_teacher_turn": "Longest teacher turn",
        "short_answers_share": "Short answers (≤3 words)",
        "avg_words_subtitle": "Ø {n} words",
        "words_unit": "words",
        "section_qualitative_analysis": "Qualitative Analysis",
        "impulses_count": "Number of Turns",
        "coded_impulses": "Coded Conversation Impulses",
        "most_frequent_codes": "Most Frequent Codes",
        "teacher_talking_rate": "Talking Share (Teacher / Students)",
        "impulses_distribution": "Distribution of Conversation Impulses",
        "impulses_coding": "Coding of Conversation Impulses",
        "results_group": "Results Group",
        "words_total": "Words Total",
        "quantity": "Quantity",
        "speaker": "Speaker",
        "caption": "Explanation",
        "section": "Section",
        "share": "Share",
        "section_first": "First third",
        "section_middle": "Middle third",
        "section_last": "Last third",
        "over_time_quant_title": "Participation over time",
        "over_time_quali_title": "Code distribution over time",
        "methods_title": "Methods text for paper",
        "methods_intro": "Auto-generated paragraph for the methods section of a manuscript. You can edit the text before copying.",
        "methods_copy": "Copy to clipboard",
        "methods_copied": "Methods text copied",
        "methods_copy_failed": "Copy failed — please select the text manually.",
        "transitions_title": "Code transitions",
        "transitions_intro": "Probability that a code (row) is followed by the next code (column). Only consecutive coded turns count; uncoded turns are skipped. With multi-coding, the first (priority-resolved) code per turn is used.",
        "transitions_n_pairs": "Transitions",
        "transitions_no_data": "At least two consecutive coded turns are needed.",
        "edit_code_hint": "Double-click the Shortcode column to correct a code.",
        "edit_code_invalid": "'{code}' is not a valid code. Valid codes: {valid}",
    },
    "options": {
        "tab_title": "Options",
        "keyring_unavailable": "No system keyring available — the API key will only be kept for this session.",
        "api_configuration": "API Configuration",
        "api_select_title": "API Selection",
        "api_select": "Use OpenAI",
        "api_groq_found": "API key for Groq found",
        "api_groq_not_found": "No API key for Groq found. Please configure.",
        "api_openai_found": "API key for openAI found",
        "api_openai_not_found": "No API key for openAI found. Please configure.",
        "api_anthropic_found": "API key for Anthropic found",
        "api_anthropic_not_found": "No API key for Anthropic found. Please configure.",
        "api_ollama_found": "Ollama cloud API key found",
        "api_ollama_not_found": "No cloud API key — using local Ollama (localhost)",
        "api_openrouter_found": "API key for OpenRouter found",
        "api_openrouter_not_found": "No API key for OpenRouter found. Please configure.",
        "api_mistral_found": "API key for Mistral found",
        "api_mistral_not_found": "No API key for Mistral found. Please configure.",
        "api_deepseek_found": "API key for DeepSeek found",
        "api_deepseek_not_found": "No API key for DeepSeek found. Please configure.",
        "api_localmind_found": "API key for LocalMind found",
        "api_localmind_not_found": "No API key for LocalMind found. Please configure.",
        "api_custom_found": "API key for the custom endpoint found",
        "api_custom_not_found": "No API key for the custom endpoint found. Please configure.",
        "provider_custom_label": "Custom endpoint (OpenAI-compatible)",
        "custom_base_url_label": "Base URL",
        "custom_base_url_hint": "OpenAI-compatible endpoint, e.g. https://host.example/v1 — such as a self-hosted vLLM server or an institutional gateway. Save the matching API key on the right as usual (OS keyring).",
        "custom_base_url_missing": "Please enter a base URL for the custom endpoint first.",
        "add_provider_button": "Add provider",
        "add_provider_title": "Add a custom provider",
        "edit_provider_button": "Edit",
        "edit_provider_title": "Edit provider",
        "delete_provider_button": "Delete provider",
        "delete_provider_title": "Delete provider",
        "delete_provider_warning": "Really delete provider “{name}”? Its model list and stored API key will be removed.",
        "provider_name_label": "Name",
        "provider_name_placeholder": "e.g. Uni-vLLM",
        "provider_incomplete": "Please enter a name and a base URL.",
        "provider_added": "Provider “{name}” added. Now save its API key and load models.",
        "provider_updated": "Provider updated.",
        "provider_deleted": "Provider deleted.",
        "fetch_models_button": "Load models from provider",
        "fetch_models_hint": "Fetches the selected provider's current model list and updates the registry. Prices of models already registered are kept; new models start at 0.",
        "fetch_models_no_key": "Save an API key for this provider first to load its model list.",
        "fetch_models_empty": "No models received from the provider.",
        "fetch_models_success": "Loaded {n} models.",
        "fetch_models_error": "Could not load models: {error}",
        "ollama_running": "Ollama is running at {url}",
        "ollama_not_running": "Ollama not reachable at {url}",
        "ollama_start_button": "Start Ollama",
        "ollama_start_error": "Ollama could not be started. Is it installed?",
        "error_title": "Error",
        "no_api_key_warning": "No API key found. Please configure an API key to use LLM features.",
        "button_change": "Change",
        "add_api_key_placeholder": "Enter API key",
        "add_api_key_save": "Save",
        "add_api_key_title": "Change API Key",
        "button_delete": "Delete",
        "delete_api_key_warning": "Are you sure you want to delete the API key?",
        "delete_api_key_confirm": "Yes, delete!",
        "delete_api_key_title": "Delete API Key",
        "button_reset": "Reset",
        "llm_models": "Models for LLM Selection",
        "available_models": "Available Models",
        "add_model": "Add Model",
        "add_model_placeholder": "e.g., gpt-4o",
        "modal_button_add": "Add",
        "add_model_title": "Add a Model",
        "model_is_local": "Model runs locally (data-protection-friendly)",
        "model_is_local_hint": "Only tick this if the model is actually executed on this machine (e.g. local Ollama). Leave unchecked for cloud endpoints like \"Ollama Cloud\" or OpenAI — otherwise they would be allowed in \"Local only\" mode by mistake.",
        "model_id": "Model ID",
        "model_provider": "Model Provider",
        "input_cost": "Cost per 1M Input Tokens (€)",
        "output_cost": "Cost per 1M Output Tokens (€)",
        "cost_placeholder": "e.g., 0.40",
        "remove_model": "Remove Model",
        "modal_remove_model_warning": "Are you sure you want to remove the selected models? This action cannot be undone.",
        "modal_remove_confirm": "Yes, remove!",
        "modal_remove_title": "Remove Models",
        "reset_model_selection_confirm": "Are you sure you want to reset the model selection to default?",
        "reset_model_selection_title": "Reset Model Selection",
        "modal_model_reset_confirm": "Yes, reset!",
        "custom_prompts": "Custom Prompts",
        "system_prompt_label": "System Prompt",
        "user_prompt_label": "User Prompt",
        "change_system_prompt": "Change System Prompt",
        "reset_system_prompt_title": "Reset System Prompt",
        "reset_system_prompt_confirm": "Are you sure you want to reset the system prompt?",
        "change_user_prompt": "Change User Prompt",
        "reset_user_prompt_title": "Reset System Prompt",
        "reset_user_prompt_confirm": "Are you sure you want to reset the system prompt?",
        "additional_options": "Additional Options",
        "teacher_name": "Teacher Name",
        "group_id": "Group ID",
        "num_students": "Group size",
        "reset_group_parameters_title": "Reset Group Parameters",
        "reset_group_parameters_confirm": "Are you sure you want to reset the group parameters?",
        "advanced_options": "Advanced",
        "streaming_switch": "Progressive display (streaming)",
        "streaming_switch_help": "When enabled, codings appear progressively during the LLM response instead of only at the end. Works for OpenAI, Anthropic, Groq, and Ollama. Default: on.",
        "streaming_switch_cancel_warning": "When streaming is disabled, a running analysis cannot be cancelled — the provider call is one blocking request.",
        "local_only_switch": "Local only (Ollama)",
        "local_only_switch_help": "When enabled, all cloud providers (OpenAI, Anthropic, Groq) are hidden — only local Ollama can be used. Useful for schools with strict data-protection rules. Default: off.",
        "cost_tracker_header": "Cost tracker (cumulative)",
        "cost_tracker_empty": "No paid analyses recorded yet.",
        "cost_tracker_total": "Total",
        "cost_tracker_col_provider": "Provider",
        "cost_tracker_col_model": "Model",
        "cost_tracker_col_cost": "Cost",
        "cost_tracker_col_runs": "Analyses",
        "cost_tracker_reset": "Reset tracker",
        "cost_tracker_reset_title": "Reset cost tracker",
        "cost_tracker_reset_confirm": "Are you sure you want to delete the accumulated cost log? This cannot be undone.",
        "self_test_header": "Self-test (test the app)",
        "self_test_intro": "Runs deterministic checks against a known demo transcript — no LLM calls, no cost. Confirms participation counts, turn statistics, intercoder measures, and the reproducibility fingerprint compute correctly.",
        "self_test_run": "Test the app",
        "self_test_all_pass": "All {n} checks passed — the app computes as expected.",
        "self_test_some_fail": "Only {passed} of {total} checks passed. Please report an issue on GitHub.",
        "self_test_col_check": "Check",
        "self_test_col_expected": "Expected",
        "self_test_col_actual": "Actual",
    },
    "feedback": {
        "tab_title": "Feedback",
        "section_title": "Teaching feedback",
        "intro_hint": "Generate research-grounded, formative feedback on the "
                      "analysed lesson — based on the teacher's T-SEDA dialogic-move "
                      "profile and the quantitative talk metrics. Review, edit and export it.",
        "disclaimer": "This feedback is an aid for reflection, not an assessment or "
                      "grade. It is generated by a language model from your analysis "
                      "data — please read it critically.",
        "empty_state": "Run an analysis with LLM coding first (Analysis tab). The "
                       "feedback is generated from the coding and the talk metrics.",
        "generate_button": "Generate feedback",
        "regenerate_button": "Regenerate",
        "generating": "Generating feedback…",
        "editor_label": "Feedback (editable)",
        "editor_hint": "You can edit the text before exporting it.",
        "preview_empty": "No feedback generated yet.",
        "copy": "Copy",
        "download_docx": "As Word (.docx)",
        "download_pdf": "As PDF",
        "pdf_failed": "PDF export failed: {error}",
        "pdf_unavailable_linux": "PDF export needs Microsoft Word and is unavailable "
                                 "on Linux. Please use the Word (.docx) download.",
        "feedback_empty": "The model returned no feedback. Please try again or pick a "
                          "different model.",
        "feedback_failed": "Feedback generation failed: {error}",
        "no_key": "No API key set for the selected provider. Add it in the Options tab.",
        "llm_hint": "The feedback is generated with this model — pre-set to the "
                    "Analysis-tab choice, changeable here (e.g. a cheaper model "
                    "than the one used for coding).",
        "doc_title": "Teaching feedback",
        "cost_estimate": "Estimated cost: € {cost}",
    },
    "info": {
        "tab_title": "Info / License",
        "dev_heading": "Development",
        "dev_current": "Current version",
        "dev_origin": "Original version",
        "license_heading": "License",
        "license_text": "This project is licensed under the **GNU Affero General Public License v3.0** (AGPL-3.0). Use, sharing and adaptation — including for commercial purposes — are permitted, but any redistribution or hosted-service deployment must offer the complete corresponding source under the same license. Redistributions must carry the license text and NOTICE file, and modified files must be marked as modified.",
        "transcription_heading": "Audio transcription (optional module)",
        "transcription_text": "The **Transcription** tab creates transcripts straight from audio recordings — **entirely on your own machine**. The audio file is never sent to any server; that is the decisive privacy advantage over cloud transcription services.\n\nTranscription is powered by the standalone open-source project [noScribe](https://github.com/kaixxx/noScribe) by Kai Dröge (Whisper speech recognition + pyannote speaker diarization), licensed under the **GPL-3.0**. noScribe is downloaded once from GitHub at your request and invoked strictly as a **separate subprocess** — TalkTrace does not link, import or bundle any noScribe code. This keeps the two projects cleanly separated for licensing (TalkTrace: AGPL-3.0 · noScribe: GPL-3.0). The Whisper and pyannote models are fetched from their respective public sources; see NOTICE for details.",
        "consent_heading": "Consent declaration (optional module)",
        "consent_text": "The **Consent** tab generates a print-ready consent declaration under **GDPR Art. 13** for the training context — intended for the case where a trainer team works *with* teachers and each teacher consents to the processing of their **own** recording. The form is pre-filled, the preview is shown live, and it exports to **Word (.docx)** or **PDF**.\n\nThe declaration reflects the actual data flow: **local transcription** (audio never leaves the device) versus the configured **AI service as a recipient** or a possible **third-country transfer**. The wording is adapted from the **CC0**-licensed [Consent-Gen-RDMO](https://github.com/berndzey/Consent-Gen-RDMO) of TU Dortmund (Bernd Zey, Wibke Kleina).\n\n⚠️ The generated declaration is an **aid, not legal advice**. Please have it reviewed by your data protection officer before use and adapt it to the requirements of your state/institution.",
    },
    "report": {
        "header": "Dialogue analysis – Group",
        "model_used": "LLM model used",
        "section_1": "1. Quantitative Distribution of Conversation Shares",
        "class_size": "Class size",
        "pupil_count": "Number of participating students",
        "participation_rate": "Participation rate",
        "table": "Table",
        "interaction_turns_teacher_pupils": "Conversation turns of teacher and students",
        "participants": "Participants",
        "teacher": "Teacher",
        "pupils": "Students",
        "quantity": "Quantity",
        "length_words": "Length in words",
        "interaction_turns": "Conversation turns",
        "figure": "Figure",
        "distribution_of_turns": "Distribution of turns",
        "section_2": "2. Qualitative Coding of Conversation Turns",
        "impulses_count": "Number of coded turns",
        "teacher_impulses": "Coded verbal turns",
        "teacher_statement": "Statement (short)",
        "speaker": "Speaker",
        "code": "Code",
        "shortcode": "Shortcode",
        "caption": "Legend",
        "fingerprint": "Reproducibility hash",
        "methods_section": "Methods text"
    },
    "system_prompts": {
        "no_code": "No code uses",
        "analysis_running": "Analysis is running.",
        "wait": "This may take a while...",
        "waiting_LLM": "Waiting for LLM response...",
        "calculating": "Calculating...",
        "error": "Error in LLM analysis",
        "try_again": "Please try again."
    },
    "stats": {
        "students": "Students",
        "teacher": "Teacher"
    },
    "testing": {
        "tab_title": "Testing",
        "section_header": "Codebook validation via intercoder agreement",
        "intro": "Upload two TalkTrace reports (.docx, .xlsx, or .html) that were generated from the same transcript with different models. The impulses are aligned by utterance text; Cohen's kappa is computed over the assigned codes. Utterances coded by only one of the two reports contribute as an 'uncoded' category.",
        "upload_report_a": "Report A (.docx / .xlsx / .html)",
        "upload_report_b": "Report B (.docx / .xlsx / .html)",
        "placeholder_report": "No report uploaded...",
        "summary_header": "Overview",
        "summary_n_pairs": "Aligned pairs",
        "summary_n_both": "Coded by both",
        "summary_only_a": "Only in A",
        "summary_only_b": "Only in B",
        "summary_percent_agreement": "Percent agreement",
        "summary_krippendorff": "Krippendorff's α",
        "summary_gwet_ac1": "Gwet's AC1",
        "summary_brennan_prediger": "Brennan-Prediger κ",
        "kappa_header": "Cohen's kappa",
        "kappa_ci_label": "95% CI",
        "per_code_header": "Per-code agreement",
        "per_code_col_code": "Code",
        "per_code_col_n_a": "n (A)",
        "per_code_col_n_b": "n (B)",
        "per_code_col_f1": "F1",
        "per_code_col_precision": "Precision",
        "per_code_col_recall": "Recall",
        "kappa_not_ready": "Please upload both reports to compute kappa.",
        "kappa_interpretation_poor": "Poor agreement",
        "kappa_interpretation_slight": "Slight agreement",
        "kappa_interpretation_fair": "Fair agreement",
        "kappa_interpretation_moderate": "Moderate agreement",
        "kappa_interpretation_substantial": "Substantial agreement",
        "kappa_interpretation_almost_perfect": "Almost perfect agreement",
        "confusion_header": "Code confusion matrix (A x B)",
        "confusion_axis_a": "Report A",
        "confusion_axis_b": "Report B",
        "parse_error_no_table": "Could not find an impulse table in the uploaded file. Please upload a TalkTrace report (.docx, .xlsx or .html).",
        "parse_error_unsupported_format": "This file format is not supported. Please use .docx, .xlsx or .html.",
        "unmatched_label": "uncoded",
        "export_report": "Export testing results",
        "export_title": "Export intercoder agreement",
        "export_intro": "Select the output format.",
        "no_data": "No testing data available to export.",
        "expert_toggle": "Expert mode",
        "expert_toggle_hint": "Advanced reliability measures (Cohen's κ, Krippendorff's α, Fleiss' κ) with significance test.",
        "expert_modal_title": "Expert mode — choose reliability measure",
        "expert_metric_label": "Measure",
        "expert_metric_cohen": "Cohen's κ (exactly 2 coders)",
        "expert_metric_krippendorff": "Krippendorff's α (2 or more coders)",
        "expert_metric_fleiss": "Fleiss' κ (3 or more coders)",
        "expert_metric_gwet": "Gwet's AC1 (2 or more coders; robust under skewed prevalence)",
        "expert_metric_brennan_prediger": "Brennan-Prediger κ (2 or more coders; uniform expected agreement)",
        "expert_n_raters_label": "Number of coders",
        "expert_file_label_template": "Coder {i} (.docx / .xlsx / .html)",
        "expert_compute": "Compute",
        "expert_cancel": "Cancel",
        "expert_reconfigure": "Change configuration",
        "expert_results_header": "Expert mode — result",
        "expert_result_value": "Value",
        "expert_result_ci": "95 % confidence interval",
        "expert_result_p_value": "p-value",
        "expert_result_n_units": "Aligned impulses",
        "expert_result_n_raters": "Number of coders",
        "expert_error_too_few_files": "Please fill all file inputs before clicking Compute.",
        "expert_error_invalid_n_for_metric": "The chosen number of coders does not match the selected measure.",
        "expert_error_compute_failed": "Computation failed — please check the inputs.",
        "expert_computing": "Computing …",
        "expert_metric_name_cohen": "Cohen's κ",
        "expert_metric_name_krippendorff": "Krippendorff's α",
        "expert_metric_name_fleiss": "Fleiss' κ",
        "expert_metric_name_gwet": "Gwet's AC1",
        "expert_metric_name_brennan_prediger": "Brennan-Prediger κ",
    },
    "autopilot": {
        "tab_title": "Autopilot",
        "intro_header": "Autopilot — everything in one click",
        "intro_body": "Upload a transcript and codebook, pick two different LLMs and the coding options — the Autopilot codes the transcript once with each model, saves both codings to history, and feeds them straight into the Testing tab for intercoder analysis.",
        "inputs_header": "1. Upload data",
        "upload_transcript": "Transcript (.txt / .docx)",
        "upload_codebook": "Codebook (.txt / .docx)",
        "status_transcript_loaded": "Transcript loaded",
        "status_transcript_missing": "No transcript loaded",
        "status_codebook_loaded": "Codebook loaded",
        "status_codebook_missing": "No codebook loaded",
        "status_source_analysis": "(reused from Analysis tab)",
        "general_header": "2. General information",
        "options_header": "3. Coding options",
        "speaker_mode_label": "Which speakers should be coded?",
        "speaker_mode_both": "Teacher and students",
        "speaker_mode_teacher": "Teacher only",
        "speaker_mode_students": "Students only",
        "coders_header": "4. Pick two LLMs",
        "coder_a_label": "Coder A",
        "coder_b_label": "Coder B",
        "start_button": "Start Autopilot",
        "cancel_after_a": "Stop after Coder A",
        "cancel_after_a_pending": "Stop requested — Coder A still finishing",
        "cancelled_after_a_banner": "Autopilot cancelled by user — Coder B not run. Coder A is available in the Results tab; an intercoder analysis is not possible without Coder B.",
        "step_coder_a": "Step 1/2 — Coding with Coder A",
        "step_coder_b": "Step 2/2 — Coding with Coder B",
        "success_done": "Done. Switch to the Testing tab for the intercoder analysis.",
        "retry_b_button": "Retry Coder B only",
        "error_prefix": "Error",
        "error_inputs_missing": "Please upload a transcript and codebook first.",
        "error_select_models": "Please select a model for both coders.",
        "error_same_model": "Coder A and Coder B must use different models.",
        "warning_same_model": "Coder A and B currently use the same model — agreement would be trivial. Please pick a different model for at least one coder.",
        "results_header": "Codings side by side",
        "results_intro": "The full impulse tables for both coders. For the intercoder analysis (Cohen's κ, Krippendorff's α, confusion matrix) head to the Testing tab.",
        "results_banner_text": "You ran the Autopilot. The two codings are on the Autopilot tab; the intercoder analysis is on the Testing tab. This tab shows only the manual single-run workflow.",
        "results_banner_active": "Active coding",
        "results_banner_swap": "Switch to {coder} ({model})",
        "quant_panel_title": "Quantitative summary (expand)",
        "quant_panel_intro": "Talk-share statistics computed from the transcript — identical for both codings since they share the same transcript.",
        "quant_box_participants": "Active students",
        "quant_box_participation_rate": "Participation rate",
        "quant_box_teacher_turns": "Teacher turns",
        "quant_box_student_turns": "Student turns",
        "quant_table_title": "Per-speaker stats",
        "quant_col_speaker": "Speaker",
        "quant_col_turns": "Turns",
        "quant_col_words_total": "Total words",
        "quant_col_words_avg": "Avg. words",
        "quant_col_words_median": "Median words",
        "make_reports_switch": "Auto-generate reports",
        "make_reports_hint": "Both coder reports are built in the background right after each coding finishes — Report A is downloadable while Coder B is still running.",
        "report_format_label": "Format",
        "report_download_a": "Download Report A",
        "report_download_b": "Download Report B",
        "report_pending": "Building report …",
        "report_failed": "Report could not be generated.",
        "report_sections_hint": "The \"over time\" sections are available only in the manual analysis flow.",
        "report_sec_quant_short": "Quantitative",
        "report_sec_quali_short": "Qualitative",
    },
    "report_options": {
        "dialog_title": "Configure report",
        "dialog_intro": "Select which sections to include and the output format.",
        "sections_label": "Content",
        "sec_quant": "Quantitative distribution (table + plot)",
        "sec_over_time_quant": "Participation over time (plot)",
        "sec_quali": "Qualitative coding (plot + impulses table)",
        "sec_over_time_quali": "Code distribution over time (plot)",
        "sec_transitions": "Code transitions (heatmap + matrix)",
        "sec_legend": "Code legend & model info",
        "format_label": "Output format",
        "format_docx": "DOCX (Word)",
        "format_pdf": "PDF",
        "format_xlsx": "XLSX (Excel)",
        "format_html": "HTML",
        "format_csv": "CSV (ZIP bundle)",
        "format_json": "JSON",
        "download_now": "Download",
        "cancel": "Cancel",
        "quali_disabled_hint": "Run LLM analysis first to enable qualitative options.",
        "no_section_selected": "Please select at least one section.",
        "pdf_unavailable": "PDF generation failed (Word or LibreOffice required).",
        "pdf_unavailable_linux": "PDF export is not supported on Linux. Please use the DOCX format instead.",
        "xlsx_unavailable": "XLSX generation requires the openpyxl package.",
        "docx_unavailable": "DOCX generation requires the python-docx package.",
        "sheet_overview": "Overview",
        "sheet_quant": "Quant",
        "sheet_quant_over_time": "Quant_over_time",
        "sheet_impulses": "Impulses",
        "sheet_quali_over_time": "Quali_over_time",
        "sheet_transitions": "Transitions"
    },
    "glossary": {
        "kappa": "Cohen's κ — chance-corrected agreement between two coders. Conventional bands: <0 worse than chance, 0–.20 slight, .21–.40 fair, .41–.60 moderate, .61–.80 substantial, .81–1.0 almost perfect. Cohen (1960).",
        "krippendorff_alpha": "Krippendorff's α — reliability coefficient for 2+ coders, robust to unbalanced distributions and missing values. Convention: ≥.80 acceptable, .67–.79 tentative. Krippendorff (2004).",
        "fleiss_kappa": "Fleiss' κ — generalisation of Cohen's κ to 3+ coders with a constant number of coders per unit. Fleiss (1971).",
        "gwet_ac1": "Gwet's AC1 — agreement coefficient robust to the kappa paradox under highly skewed code prevalence. Gwet (2008).",
        "brennan_prediger": "Brennan-Prediger κ — agreement against uniformly distributed expected agreement; less sensitive to rare codes than Cohen's κ. Brennan & Prediger (1981).",
        "percent_agreement": "Percent agreement — share of units where both coders assigned the same code. Intuitive baseline; ignores chance agreement.",
        "f1": "F1 score — harmonic mean of precision and recall for one code. 1.0 = perfect, 0 = nothing matched.",
        "precision": "Precision — share of correct assignments out of all of coder B's occurrences of this code. \"When coder B picks this code, how often does coder A also pick it?\"",
        "recall": "Recall — share of correct assignments out of all actual (coder A) occurrences of this code. \"When coder A picks this code, how often does coder B also pick it?\"",
        "confusion_matrix": "Confusion matrix — table of code mix-ups between two coders. Diagonal = agreement, off-diagonal = mix-ups.",
        "ci": "95% confidence interval (bootstrap, n=1000 resamples) — range that contains the true value with 95% probability.",
        "p_value": "p-value — probability of observing the current (or a more extreme) result under H₀ (κ=0). ***<.001, **<.01, *<.05, n.s. otherwise.",
        "n_pairs": "Aligned pairs — total number of impulses coded in at least one report.",
        "n_both": "Coded by both — number of impulses present in both reports.",
        "n_only": "Only in one — impulses captured by only one report (counted as \"unmatched\")."
    },
    "onboarding": {
        "demo_button": "Try with example data",
        "demo_loaded": "Example loaded — explore the Results tab.",
        "welcome_title": "Welcome to TalkTrace AI",
        "welcome_intro": "Three quick steps to get started:",
        "welcome_step_1": "Add an API key under Options (or use Ollama locally).",
        "welcome_step_2": "Upload a transcript and a codebook in the Analysis tab.",
        "welcome_step_3": "Click \"Analyze\" — quantitative results appear immediately, qualitative coding once the LLM responds.",
        "welcome_demo_hint": "Or click \"Try with example data\" to skip setup and explore.",
        "welcome_close": "Got it",
        "welcome_dont_show": "Don't show again",
        "empty_results_message": "Upload a transcript and a codebook in the Analysis tab and click \"Analyze\".",
        "quickstart_title": "Quick start",
        "quickstart_api_key": "API key configured",
        "quickstart_model": "Model selected",
        "quickstart_transcript": "Transcript uploaded",
        "quickstart_codebook": "Codebook uploaded",
        "quickstart_analysis_done": "Analysis complete",
        "quickstart_status_ok": "Ready",
        "quickstart_status_pending": "Steps left",
        "tooltip_group_id": "Free-form label for this discussion. Used as report header and filename suffix.",
        "tooltip_num_pupils": "Total size of the group (e.g. all students in the class). Used as the reference for the participation rate (active speakers / total) — please enter manually.",
        "tooltip_name_teacher": "How the teacher is labeled in the transcript (e.g. TEACHER, LEHRER, Frau Müller). Must match the transcript exactly.",
        "tooltip_upload_transcript": "Plain text or .docx. Format: one turn per line, e.g. \"S01: ...\". Use \"Convert transcript\" if your file uses SPEAKER_00 headers.",
        "tooltip_upload_codebook": "List of codes the LLM may use. Plain text or .docx. Each code with shortcode + brief description.",
        "tooltip_llm_switch": "Toggles qualitative coding via LLM. Off = quantitative stats only (no API call, free).",
        "tooltip_model_select": "Model used for qualitative coding. Larger models cost more but produce better codes.",
        "dp_title": "Data-protection notice",
        "dp_intro_strong": "Please read before first use.",
        "dp_intro_body": "TalkTrace sends transcripts and codebooks to the selected LLM provider. With OpenAI, Anthropic and Groq the data leaves the European Economic Area (US-hosted servers). Please confirm which kind of data you will work with:",
        "dp_choice_label": "What will you work with?",
        "dp_choice_consent": "I will only use transcripts for which the speakers have given written consent to AI-based processing (including in the US).",
        "dp_choice_fictive": "I will only use fictive test data (e.g. invented or AI-generated) without any link to real people.",
        "dp_consent_hint": "Tip: if you only want to use local models, switch on \"Local only (Ollama)\" under Options → Advanced. Cloud models (including \"Ollama Cloud\") are then automatically hidden.",
        "dp_confirm": "I acknowledge",
        "dp_pick_required": "Please pick one of the two options before continuing."
    },
    "start": {
        "tab_title": "Start",
        "intro_headline": "Welcome to TalkTrace AI",
        "intro_body": "TalkTrace analyses classroom and small-group conversations: quantitative metrics, qualitative LLM coding, and exportable reports. Pick an entry point below, or follow the workflow from left to right.",
        "workflow_title": "How it works",
        "workflow_audio": "Audio",
        "workflow_transcript": "Transcript",
        "workflow_analysis": "Analysis",
        "workflow_feedback": "Feedback",
        "workflow_export": "Export",
        "status_done": "done",
        "status_pending": "pending",
        "tiles_title": "Quick start",
        "tile_tseda_title": "T-SEDA analysis",
        "tile_tseda_body": "Analyse classroom talk with the built-in T-SEDA codebook — just upload a transcript.",
        "tile_audio_title": "Start with audio",
        "tile_audio_body": "Transcribe a recording locally — the audio never leaves your machine.",
        "tile_transcript_title": "Start with a transcript",
        "tile_transcript_body": "Upload a transcript and a codebook, then run the analysis.",
        "tile_resume_title": "Load last session",
        "tile_resume_body": "Pick up a saved analysis from the history.",
        "tile_demo_title": "View the demo",
        "tile_demo_body": "Load a ready-made example — no API key needed.",
        "config_title": "Current configuration",
        "config_line_template": "Provider: {provider} · Model: {model} · {status}",
        "config_line_ready": "ready",
        "config_line_no_key": "no API key set",
        "config_line_no_provider": "No LLM configured yet — set it up in the Analysis tab.",
        "quickstart_title": "Quick start",
        "whats_new_title": "What's new?",
        "whats_new_1": "T-SEDA template: built-in codebook in one click — just upload a transcript.",
        "whats_new_2": "Multi-coding with confidence: up to 2 codes per turn in dedicated columns + a second review pass for uncoded turns.",
        "whats_new_3": "Custom OpenAI-compatible endpoints + model refresh for every provider.",
        "dp_section_title": "Data protection",
        "dp_intro_strong": "Please confirm before your first analysis.",
        "dp_intro_body": "TalkTrace sends transcripts and codebooks to the selected LLM provider. With OpenAI, Anthropic and Groq the data leaves the European Economic Area (US-hosted servers). Please confirm which kind of data you will work with:",
        "dp_choice_consent": "I will only use transcripts for which the speakers have given written consent to AI-based processing (including in the US).",
        "dp_choice_fictive": "I will only use fictive test data (e.g. invented or AI-generated) without any link to real people.",
        "dp_choice_self": "I analyse only my own utterances (e.g. as the teacher, my own contributions); no other person's data is processed.",
        "dp_confirm": "I acknowledge",
        "dp_pick_required": "Please pick one of the options before continuing.",
        "dp_status_pending": "Data protection not yet acknowledged — required before the first analysis.",
        "dp_status_ok": "Data protection acknowledged:",
        "dp_kind_consent": "consent obtained",
        "dp_kind_fictive": "fictive test data",
        "dp_kind_self": "own utterances only",
        "dp_change": "Change"
    }
}
